(() => {
'use strict';
const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];
const DB_KEY='nexus_x_inventory_v1';
const SETTINGS_KEY='nexus_x_settings_v1';
const WEB_TIMEOUT=6500;
const state={inventory:[],view:'dashboard',web:false,stream:null,scanBusy:false,docs:[],lastQuery:'',activity:[],favorites:new Set(JSON.parse(localStorage.getItem('nexus_x_favorites_v1')||'[]'))};
const MASTER_URL='inventory.json';

function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function norm(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();}
function canonicalId(v){let s=String(v??'').trim(); const m=s.match(/(?:NEXUS[-_:]?X|X|NX)[-_: ]*(\d{1,6})$/i)||s.match(/^(\d{1,6})$/); return m?`NEXUS-X-${String(Number(m[1])).padStart(4,'0')}`:s;}
function validId(v){return /^NEXUS-X-\d{4}$/.test(String(v||''));}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),3200);}
function setView(name){state.view=name;$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name)); if(name==='inventory')renderInventory(); if(name==='reports')renderReports(); if(name==='settings')renderDiagnostics();}
function saveInventory(){localStorage.setItem(DB_KEY,JSON.stringify(state.inventory));}
function saveActivity(text){state.activity.unshift({text,at:new Date().toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})});state.activity=state.activity.slice(0,8);renderActivity();}
function validateInventory(records, expected=111){
 if(!Array.isArray(records)||!records.length)throw new Error('La base no contiene registros.');
 const ids=records.map(x=>x.id); const dup=ids.filter((x,i)=>ids.indexOf(x)!==i); if(dup.length)throw new Error(`IDs duplicados: ${[...new Set(dup)].join(', ')}`);
 const bad=records.filter(x=>!validId(x.id)); if(bad.length)throw new Error(`Hay ${bad.length} IDs con formato inválido.`);
 if(expected!==null && records.length!==expected)throw new Error(`Se esperaban ${expected} registros y llegaron ${records.length}.`);
 return true;
}
function normalizeRecord(r, fallbackIndex){
 const id=canonicalId(r.id||r.ID_NEXUS_X||r.codigo||r.ID||'');
 return {id,record:Number(r.record||fallbackIndex||0),originalNumber:String(r.originalNumber??r.Nº_Original??''),name:String(r.name??r.Sustancia_Mezcla_Material??r.nombre??''),formula:String(r.formula??r.Formula??''),physicalState:String(r.physicalState??r.Estado_Fisico??''),presentation:String(r.presentation??r.Presentacion??''),originalPackage:String(r.originalPackage??r.Envase_Original??''),expiry:String(r.expiry??r.Fecha_Envasado_Vencimiento??''),location:String(r.location??r.Ubicacion_Armario??''),notes:String(r.notes??r.Observaciones??''),source:String(r.source??'')};
}
async function loadMaster(){
 try{const res=await fetch(MASTER_URL,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();const recs=data.records.map(normalizeRecord);validateInventory(recs,111);state.inventory=recs;saveInventory();saveActivity('Base maestra JSON cargada y validada');}
 catch(e){console.warn('Master JSON',e);try{const cached=JSON.parse(localStorage.getItem(DB_KEY)||'null');validateInventory(cached,111);state.inventory=cached;saveActivity('Base local recuperada');}catch(_){state.inventory=[];saveActivity('No se pudo cargar la base maestra');}}
 renderAll();
}
function renderDashboard(){
 const inv=state.inventory;$('#statInventory').textContent=inv.length;$('#statLocations').textContent=new Set(inv.map(x=>x.location).filter(Boolean)).size;$('#statFormula').textContent=inv.filter(x=>x.formula).length;$('#taskFormula').textContent=inv.filter(x=>!x.formula).length;$('#taskLocation').textContent=inv.filter(x=>!x.location).length;$('#taskDocs').textContent=state.docs.length;$('#legendKnown').textContent=inv.length;$('#statSystem').textContent=validId(inv[0]?.id||'NEXUS-X-0000')?'OK':'REVISAR';}
function renderActivity(){const el=$('#activity');el.innerHTML=state.activity.length?state.activity.map(a=>`<div class="activity"><span>●</span><span>${escapeHtml(a.text)}</span><span class="time">${a.at}</span></div>`).join(''):'<div class="empty">Sin actividad todavía.</div>';}
function inventoryStatus(r){const s=norm(r.expiry);if(!s||s.includes('no presenta')||s.includes('desconoce'))return ['ok','SIN VENCIMIENTO']; const d=new Date(r.expiry);if(Number.isNaN(d.getTime()))return ['warn','REVISAR FECHA'];const days=Math.ceil((d-new Date())/86400000);return days<0?['danger','VENCIDO']:days<=30?['danger',`URGENTE · ${days} d`]:days<=90?['warn',`PRÓXIMO · ${days} d`]:['ok',`VIGENTE · ${days} d`];}
function filteredInventory(){const q=norm($('#inventorySearch')?.value||'');const loc=$('#locationFilter')?.value||'';const status=$('#statusFilter')?.value||'';return state.inventory.filter(r=>{const st=inventoryStatus(r)[0];return (!loc||r.location===loc)&&(!status||st===status)&&(!q||norm(Object.values(r).join(' ')).includes(q));});}
function renderInventory(){const locs=[...new Set(state.inventory.map(x=>x.location).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));const sel=$('#locationFilter');if(sel){const cur=sel.value;sel.innerHTML='<option value="">Todas las ubicaciones</option>'+locs.map(x=>`<option>${escapeHtml(x)}</option>`).join('');if(locs.includes(cur))sel.value=cur;}const sf=$('#statusFilter');const statusCur=sf?.value||'';if(sf)sf.value=statusCur;const rows=filteredInventory();$('#inventorySummary').textContent=`Mostrando ${rows.length} de ${state.inventory.length} registros.`;const counts={ok:0,warn:0,danger:0};state.inventory.forEach(r=>counts[inventoryStatus(r)[0]]++);const quick=$('#inventoryQuick');if(quick)quick.innerHTML=`<button class="btn" data-qfilter="">Todos · ${state.inventory.length}</button><button class="btn teal" data-qfilter="ok">Vigentes · ${counts.ok}</button><button class="btn" data-qfilter="warn">Revisar · ${counts.warn}</button><button class="btn danger" data-qfilter="danger">Alertas · ${counts.danger}</button>`;const table=$('#inventoryTable');table.innerHTML=rows.length?`<table><thead><tr><th>ID</th><th>Sustancia / material</th><th>Fórmula</th><th>Estado</th><th>Presentación</th><th>Ubicación</th><th>Vencimiento</th><th></th></tr></thead><tbody>${rows.map(r=>{const st=inventoryStatus(r);const fav=state.favorites.has(r.id);return `<tr><td class="id">${escapeHtml(r.id)}</td><td><strong>${escapeHtml(r.name)}</strong><br><span class="muted">Original: ${escapeHtml(r.originalNumber)}</span></td><td>${escapeHtml(r.formula||'—')}</td><td>${escapeHtml(r.physicalState||'—')}</td><td>${escapeHtml(r.presentation||'—')}</td><td>${escapeHtml(r.location||'—')}</td><td><span class="badge ${st[0]}">${escapeHtml(st[1])}</span></td><td><div class="row-actions"><button class="favorite-btn ${fav?'active':''}" title="${fav?'Quitar de favoritos':'Agregar a favoritos'}" data-fav="${escapeHtml(r.id)}">${fav?'★':'☆'}</button><button class="btn" data-edit="${escapeHtml(r.id)}">Abrir</button></div></td></tr>`}).join('')}</tbody></table>`:'<div class="empty">No hay coincidencias.</div>';$$('[data-edit]').forEach(b=>b.addEventListener('click',()=>openItem(b.dataset.edit)));$$('[data-fav]').forEach(b=>b.addEventListener('click',()=>toggleFavorite(b.dataset.fav)));$$('[data-qfilter]').forEach(b=>b.addEventListener('click',()=>{$('#statusFilter').value=b.dataset.qfilter;renderInventory()}));}
function openItem(id){const r=state.inventory.find(x=>x.id===id);if(!r)return;$('#itemModalTitle').textContent=r.id;$('#fId').value=r.id;$('#fOriginal').value=r.originalNumber;$('#fName').value=r.name;$('#fFormula').value=r.formula;$('#fState').value=r.physicalState;$('#fPresentation').value=r.presentation;$('#fPackage').value=r.originalPackage;$('#fExpiry').value=r.expiry;$('#fLocation').value=r.location;$('#fNotes').value=r.notes;$('#deleteItemBtn').style.display='inline-block';$('#itemModal').classList.add('open');}
function newItem(){['fId','fOriginal','fName','fFormula','fState','fPresentation','fPackage','fExpiry','fLocation','fNotes'].forEach(id=>$('#'+id).value='');$('#fId').value=nextId();$('#deleteItemBtn').style.display='none';$('#itemModalTitle').textContent='Nuevo registro';$('#itemModal').classList.add('open');}
function nextId(){let max=0;for(const r of state.inventory){const m=r.id.match(/(\d{4})$/);if(m)max=Math.max(max,Number(m[1]));}return `NEXUS-X-${String(max+1).padStart(4,'0')}`;}
function saveItem(){const r=normalizeRecord({id:$('#fId').value,originalNumber:$('#fOriginal').value,name:$('#fName').value,formula:$('#fFormula').value,physicalState:$('#fState').value,presentation:$('#fPresentation').value,originalPackage:$('#fPackage').value,expiry:$('#fExpiry').value,location:$('#fLocation').value,notes:$('#fNotes').value},state.inventory.length+1);if(!validId(r.id)||!r.name){toast('ID NEXUS-X válido y nombre son obligatorios.');return}const idx=state.inventory.findIndex(x=>x.id===r.id);if(idx>=0)state.inventory[idx]=r;else{if(state.inventory.some(x=>x.id===r.id)){toast('Ese ID ya existe.');return}state.inventory.push(r)}saveInventory();saveActivity(`${idx>=0?'Registro actualizado':'Registro creado'}: ${r.id}`);$('#itemModal').classList.remove('open');renderAll();}
function deleteItem(){const id=$('#fId').value;if(!confirm(`¿Eliminar ${id}?`))return;state.inventory=state.inventory.filter(x=>x.id!==id);saveInventory();saveActivity(`Registro eliminado: ${id}`);$('#itemModal').classList.remove('open');renderAll();}
function searchLocal(q){const nq=norm(q);if(!nq)return[];return state.inventory.map(r=>{const hay=norm(Object.values(r).join(' '));let score=0;if(norm(r.id)===nq)score+=100;if(norm(r.name).includes(nq))score+=45;if(r.formula&&norm(r.formula).includes(nq))score+=35;if(norm(r.location).includes(nq))score+=20;if(hay.includes(nq))score+=10;return {r,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,12);}
function renderResearchLabs(hits,q){
 const evidence=$('#evidenceLab'),claims=$('#claimsLab'),graph=$('#graphLab'),audit=$('#auditLab');
 [evidence,claims,graph,audit].forEach(x=>x.innerHTML='');
 if(!hits.length)return;
 evidence.innerHTML='<h3>Laboratorio de evidencia</h3>'+hits.slice(0,8).map(({r,score})=>`<div class="result-card"><strong>${escapeHtml(r.id)} · ${escapeHtml(r.name)}</strong><div class="muted">Evidencia primaria: registro local · score ${score}</div><div>${escapeHtml(r.formula||'Sin fórmula')} · ${escapeHtml(r.physicalState||'Estado no informado')} · ${escapeHtml(r.location||'Ubicación no informada')}</div><div class="footer-note">Fuente: ${escapeHtml(r.source||'inventory.json')}</div></div>`).join('');
 const claimRows=[];hits.slice(0,8).forEach(({r})=>{claimRows.push([`${r.id} corresponde a ${r.name}`,'directa',r.id]);if(r.location)claimRows.push([`${r.name} está ubicado en ${r.location}`,'directa',r.id]);if(r.formula)claimRows.push([`${r.name} tiene fórmula ${r.formula}`,'directa',r.id]);});
 claims.innerHTML='<h3>Claims</h3>'+claimRows.map(c=>`<div class="result-card"><strong>${escapeHtml(c[0])}</strong><div class="muted">Tipo: ${c[1]} · evidencia: ${escapeHtml(c[2])}</div></div>`).join('');
 const nodes=[];const edges=[];const add=(id,label,type)=>{if(!nodes.some(n=>n.id===id))nodes.push({id,label,type})};hits.slice(0,6).forEach(({r})=>{add('i:'+r.id,r.id,'inventory');add('n:'+r.name,r.name,'material');edges.push(['i:'+r.id,'n:'+r.name,'contiene']);if(r.formula){add('f:'+r.formula,r.formula,'formula');edges.push(['i:'+r.id,'f:'+r.formula,'formula'])}if(r.location){add('l:'+r.location,r.location,'location');edges.push(['i:'+r.id,'l:'+r.location,'ubicación'])}});
 graph.innerHTML='<h3>Grafo NEXUS-X</h3><div class="notice">'+nodes.length+' nodos · '+edges.length+' relaciones · consulta: '+escapeHtml(q)+'</div><div class="section" style="display:flex;flex-wrap:wrap;gap:8px">'+nodes.map(n=>`<span class="badge">${n.type}: ${escapeHtml(n.label)}</span>`).join('')+'</div><div class="footer-note">'+edges.map(e=>`${escapeHtml(e[0].slice(2))} → ${escapeHtml(e[2])} → ${escapeHtml(e[1].slice(2))}`).join('<br>')+'</div>';
 audit.innerHTML='<h3>Auditoría</h3><div class="diagnostic">'+escapeHtml(JSON.stringify({query:q,localFirst:true,localHits:hits.length,webEnabled:state.web,adversarial:$('#adversarial').checked,steps:['normalización','búsqueda local','ranking','separación de evidencia','web opcional'],timestamp:new Date().toISOString()},null,2))+'</div>';
}
function setResearchTab(tab){$$('.research-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));['evidenceLab','claimsLab','graphLab','auditLab'].forEach(id=>$('#'+id).style.display='none');if(tab==='evidence')$('#evidenceLab').style.display='block';if(tab==='claims')$('#claimsLab').style.display='block';if(tab==='graph')$('#graphLab').style.display='block';if(tab==='audit')$('#auditLab').style.display='block';if(tab==='answer')$('#researchResults').style.display='block';else $('#researchResults').style.display='none';}
function runResearch(){const q=$('#researchInput').value.trim();if(!q){toast('Escribí una consulta.');return}state.lastQuery=q;saveQueryHistory(q);const hits=searchLocal(q);$('#researchLocal').innerHTML=hits.length?`<strong>${hits.length} coincidencia(s) local(es).</strong> NEXUS-X prioriza esta evidencia antes de Internet.`:'No hay coincidencias locales exactas. Podés activar Internet si necesitás contexto externo.';$('#researchResults').innerHTML=hits.map(({r,score})=>`<div class="result-card"><strong>${escapeHtml(r.name)} <span class="id">${escapeHtml(r.id)}</span></strong><div class="muted">${escapeHtml(r.formula||'Sin fórmula')} · ${escapeHtml(r.physicalState||'—')} · ${escapeHtml(r.location||'—')}</div><div class="footer-note">Puntaje local: ${score}</div><button class="btn section" data-result-id="${escapeHtml(r.id)}">Ver ficha</button></div>`).join('');$$('[data-result-id]').forEach(b=>b.addEventListener('click',()=>openItem(b.dataset.resultId)));renderResearchLabs(hits,q);setResearchTab('answer');if(state.web)runWeb(q);else $('#webResults').innerHTML='';$('#chat').innerHTML=`<div class="msg bot">Contexto local preparado: ${hits.length} registro(s). La respuesta debe distinguir evidencia de inferencia.</div>`;}
async function fetchTimeout(url,options={},ms=WEB_TIMEOUT){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...options,signal:c.signal})}finally{clearTimeout(t)}}
async function runWeb(q){const box=$('#webResults');box.innerHTML='<div class="notice">🌐 Buscando Internet… si el proveedor falla, NEXUS-X seguirá funcionando localmente.</div>';const providers=[['DuckDuckGo','https://api.duckduckgo.com/?q='+encodeURIComponent(q)+'&format=json&no_html=1&skip_disambig=1'],['Jina Reader','https://r.jina.ai/http://www.google.com/search?q='+encodeURIComponent(q)]];for(const [name,url] of providers){try{const res=await fetchTimeout(url,{headers:{Accept:'application/json,text/plain'}},WEB_TIMEOUT);if(!res.ok)throw new Error('HTTP '+res.status);const text=await res.text();const parsed=name==='DuckDuckGo'?parseDDG(JSON.parse(text)):parseJina(text);if(parsed.length){box.innerHTML=`<div class="notice"><strong>🌐 ${escapeHtml(name)}</strong> · resultados externos (no son evidencia del inventario).</div>`+parsed.slice(0,8).map(x=>`<div class="result-card"><strong>${escapeHtml(x.title)}</strong><div class="muted">${escapeHtml(x.snippet||'')}</div>${x.url?`<a href="${escapeHtml(x.url)}" target="_blank" rel="noopener noreferrer">Abrir fuente</a>`:''}</div>`).join('');return}}catch(e){console.warn(name,e)}}box.innerHTML='<div class="notice warn">Internet no devolvió resultados en este momento. Esto no afecta la búsqueda local.</div>';}
function parseDDG(d){const out=[];if(d.AbstractText)out.push({title:d.Heading||'Resumen',snippet:d.AbstractText,url:d.AbstractURL});for(const x of (d.RelatedTopics||[])){if(x.Text)out.push({title:x.Text.slice(0,100),snippet:x.Text,url:x.FirstURL})}return out;}
function parseJina(t){const out=[];const lines=t.split(/\n+/).map(x=>x.trim()).filter(Boolean);for(let i=0;i<lines.length&&out.length<12;i++){const m=lines[i].match(/^\[?\d+\]?\s*\.?\s*(.+)$/);if(m&&lines[i+1])out.push({title:m[1],snippet:lines[i+1].slice(0,300),url:(lines[i+2]||'').match(/https?:\/\/\S+/)?.[0]||''})}return out;}
async function loadScript(url,globalName){if(window[globalName])return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=url;s.onload=resolve;s.onerror=()=>reject(new Error('No se pudo cargar '+url));document.head.appendChild(s)})}
async function importExcel(file){try{await loadScript('https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js','XLSX');const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true,raw:false,defval:''});const rows=[];for(const name of wb.SheetNames){const data=XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:''});if(!data.length)continue;let hi=0,best=-1;data.slice(0,12).forEach((row,i)=>{const s=row.map(norm).join(' ');const score=row.filter(Boolean).length+(/(id|codigo|nombre|material|sustancia|formula|ubicacion|stock)/.test(s)?8:0);if(score>best){best=score;hi=i}});const headers=data[hi].map((x,i)=>String(x||`Campo ${i+1}`).trim());for(let i=hi+1;i<data.length;i++){const raw={};headers.forEach((h,j)=>raw[h]=data[i][j]??'');if(Object.values(raw).some(v=>String(v).trim()))rows.push(raw)}}if(!rows.length)throw new Error('No se encontraron filas.');const mapped=rows.map((r,i)=>{const keys=Object.keys(r);const pick=(...names)=>{const k=keys.find(k=>names.includes(norm(k)));return k?r[k]:''};return normalizeRecord({id:pick('id nexus x','id_nexus_x','id','codigo nexus','codigo'),originalNumber:pick('nº original','n° original','numero original','nro original'),name:pick('sustancia mezcla material','sustancia','mezcla','material','nombre','descripcion'),formula:pick('formula','fórmula','formula quimica','fórmula química'),physicalState:pick('estado fisico','estado físico'),presentation:pick('presentacion','presentación'),originalPackage:pick('envase original'),expiry:pick('fecha envasado vencimiento','vencimiento','fecha vencimiento'),location:pick('ubicacion armario','ubicación armario','ubicacion','ubicación','estante'),notes:pick('observaciones','notas','comments')},i+1)});let generated=0;const used=new Set(mapped.filter(r=>validId(r.id)).map(r=>r.id));let next=1;mapped.forEach(r=>{if(!validId(r.id)){while(used.has(`NEXUS-X-${String(next).padStart(4,'0')}`))next++;r.id=`NEXUS-X-${String(next).padStart(4,'0')}`;used.add(r.id);next++;generated++}});validateInventory(mapped,null);state.inventory=mapped;saveInventory();saveActivity(`Excel importado: ${mapped.length} filas · ${generated} IDs normalizados`);renderAll();toast(`Excel cargado: ${mapped.length} registros.`)}catch(e){console.error(e);toast('No se importó el Excel: '+e.message)}}
async function importWord(file){try{await loadScript('https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js','JSZip');const zip=await JSZip.loadAsync(await file.arrayBuffer());const xml=await zip.file('word/document.xml').async('text');const doc=new DOMParser().parseFromString(xml,'application/xml');const texts=[...doc.getElementsByTagName('w:p')].map(p=>[...p.getElementsByTagName('w:t')].map(t=>t.textContent||'').join('').trim()).filter(Boolean);const text=texts.join('\n');const blocks=text.split(/(?=REGISTRO\s+\d+)/).slice(1);const labels=['ID_NEXUS_X','Nº_Original','Sustancia_Mezcla_Material','Formula','Estado_Fisico','Presentacion','Envase_Original','Fecha_Envasado_Vencimiento','Ubicacion_Armario'];const re=new RegExp('('+labels.map(x=>x.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')).join('|')+')\\s*:\\s*([\\s\\S]*?)(?=\\s+(?:'+labels.join('|')+')\\s*:|$)','g');const records=[];for(const b of blocks){const mm=b.match(/^REGISTRO\s+(\d+)/);if(!mm)continue;const o={record:Number(mm[1])};let m;while((m=re.exec(b))){o[m[1]]=(m[2]||'').replace(/\s+/g,' ').trim()}re.lastIndex=0;records.push(normalizeRecord(o,records.length+1))}validateInventory(records,111);state.inventory=records;saveInventory();saveActivity('Word maestro cargado, validado y aplicado atómicamente');renderAll();toast('Word maestro validado: 111 registros.')}catch(e){console.error(e);toast('Word rechazado; se conservó la base anterior. '+e.message)}}
function qrExtractId(raw){const text=String(raw??'').trim();const m=text.match(/(?:NEXUS[-_:]?X|NX)[-_: ]*(\d{1,6})/i);return m?`NEXUS-X-${String(Number(m[1])).padStart(4,'0')}`:canonicalId(text.replace(/[?#].*$/,'').replace(/\/+$/,''));}
async function loadQrFallback(){await loadScript('https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.js','jsQR');}
async function decodeQrImage(file){try{if('BarcodeDetector' in window){const bitmap=await createImageBitmap(file);const detector=new BarcodeDetector({formats:['qr_code']});const codes=await detector.detect(bitmap);bitmap.close();if(codes[0]?.rawValue){processQr(codes[0].rawValue);return}}await loadQrFallback();const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');const scale=Math.min(1,1280/Math.max(bitmap.width,bitmap.height));canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const img=ctx.getImageData(0,0,canvas.width,canvas.height);const code=window.jsQR(img.data,img.width,img.height,{inversionAttempts:'attemptBoth'});if(!code?.data)throw new Error('No se detectó un QR en la imagen.');processQr(code.data)}catch(e){console.error(e);toast('No se pudo leer el QR: '+e.message)}}
async function startQr(){if(!navigator.mediaDevices?.getUserMedia){toast('La cámara no está disponible en este navegador/contexto. Usá HTTPS o carga un ID manual.');return}stopQr();try{state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});const v=$('#qrVideo');v.srcObject=state.stream;await v.play();$('#qrStage').classList.remove('black');$('#qrStageText').textContent='Buscando código…';if('BarcodeDetector' in window){const detector=new BarcodeDetector({formats:['qr_code']});state.scanBusy=false;const loop=async()=>{if(!state.stream||state.scanBusy)return;try{const codes=await detector.detect(v);if(codes[0]?.rawValue){state.scanBusy=true;processQr(codes[0].rawValue);return}}catch(e){}requestAnimationFrame(loop)};requestAnimationFrame(loop)}else{try{await loadQrFallback();}catch(e){$('#qrStageText').textContent='Escáner automático no disponible. Usá imagen o ID manual.';return}const canvas=document.createElement('canvas');const ctx=canvas.getContext('2d',{willReadFrequently:true});state.scanBusy=false;const loop=()=>{if(!state.stream||state.scanBusy)return;try{if(v.readyState>=2){canvas.width=v.videoWidth||640;canvas.height=v.videoHeight||480;ctx.drawImage(v,0,0,canvas.width,canvas.height);const img=ctx.getImageData(0,0,canvas.width,canvas.height);const code=window.jsQR(img.data,img.width,img.height,{inversionAttempts:'attemptBoth'});if(code?.data){state.scanBusy=true;processQr(code.data);return}}}catch(e){}requestAnimationFrame(loop)};requestAnimationFrame(loop)}}catch(e){console.error(e);toast('No se pudo iniciar la cámara: '+e.message)}}
function stopQr(){if(state.stream){state.stream.getTracks().forEach(t=>t.stop());state.stream=null}state.scanBusy=false;const v=$('#qrVideo');if(v)v.srcObject=null;$('#qrStage')?.classList.add('black');if($('#qrStageText'))$('#qrStageText').textContent='Cámara detenida'}
function processQr(raw){const id=qrExtractId(raw);const r=state.inventory.find(x=>x.id===id);stopQr();$('#qrStage').classList.add('black');if(r){$('#qrResult').innerHTML=`<div class="notice"><strong>${escapeHtml(r.id)}</strong><br>${escapeHtml(r.name)}<br><span class="muted">${escapeHtml(r.formula||'Sin fórmula')} · ${escapeHtml(r.location||'Sin ubicación')}</span></div><button class="btn primary section" id="qrOpenResult">Abrir ficha</button>`;$('#qrOpenResult').onclick=()=>openItem(r.id);saveActivity(`QR leído: ${r.id}`)}else $('#qrResult').innerHTML=`<div class="notice warn">Código detectado: <strong>${escapeHtml(id||raw)}</strong><br>No existe un registro con ese ID.</div>`;}
async function importPdf(file){try{await loadScript('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js','pdfjsLib');const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;state.docs.push({name:file.name,pages:pdf.numPages});$('#documentList').innerHTML=state.docs.map(d=>`<div class="result-card"><strong>${escapeHtml(d.name)}</strong><div class="muted">${d.pages} página(s)</div></div>`).join('');saveActivity(`PDF cargado: ${file.name} · ${pdf.numPages} páginas`);renderDashboard()}catch(e){toast('No se pudo abrir el PDF: '+e.message)}}
async function aiQuery(){const q=$('#aiInput').value.trim();if(!q)return;const key=sessionStorage.getItem('nexus_ai_key')||'';const endpoint=sessionStorage.getItem('nexus_ai_endpoint')||'';const model=sessionStorage.getItem('nexus_ai_model')||'';$('#chat').insertAdjacentHTML('beforeend',`<div class="msg user">${escapeHtml(q)}</div>`);$('#aiInput').value='';if(!key||!endpoint){$('#chat').insertAdjacentHTML('beforeend','<div class="msg bot">IA no configurada. La búsqueda local funciona sin API Key.</div>');return}const hits=searchLocal(state.lastQuery||q).slice(0,8);const context=hits.map(x=>`${x.r.id} | ${x.r.name} | ${x.r.formula} | ${x.r.location} | ${x.r.physicalState}`).join('\n');try{const res=await fetchTimeout(endpoint,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+key},body:JSON.stringify({model,messages:[{role:'system',content:'Sos NEXUS-X. Respondé en español. Separá evidencia de inferencia y no inventes datos.'},{role:'user',content:`Contexto local:\n${context}\n\nConsulta:\n${q}`}],temperature:0.2})},12000);if(!res.ok)throw new Error('HTTP '+res.status);const d=await res.json();const ans=d.choices?.[0]?.message?.content||d.output_text||'Sin respuesta';$('#chat').insertAdjacentHTML('beforeend',`<div class="msg bot">${escapeHtml(ans)}</div>`)}catch(e){$('#chat').insertAdjacentHTML('beforeend',`<div class="msg bot">No se pudo consultar la IA: ${escapeHtml(e.message)}. La base local sigue disponible.</div>`)}$('#chat').scrollTop=$('#chat').scrollHeight;}
function exportCsv(){const headers=['ID_NEXUS_X','Nº_Original','Sustancia_Mezcla_Material','Formula','Estado_Fisico','Presentacion','Envase_Original','Fecha_Envasado_Vencimiento','Ubicacion_Armario','Observaciones'];const map=r=>[r.id,r.originalNumber,r.name,r.formula,r.physicalState,r.presentation,r.originalPackage,r.expiry,r.location,r.notes];const csv=[headers,...state.inventory.map(map)].map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n');download('NEXUS-X-inventario.csv',new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));}
function exportReport(){const report={generatedAt:new Date().toISOString(),records:state.inventory.length,idsValid:state.inventory.every(x=>validId(x.id)),uniqueIds:new Set(state.inventory.map(x=>x.id)).size,locations:[...new Set(state.inventory.map(x=>x.location).filter(Boolean))],documents:state.docs};download('NEXUS-X-informe.json',new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));}
function download(name,blob){const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function renderReports(){const inv=state.inventory;$('#reportSummary').innerHTML=`<p><strong>${inv.length}</strong> registros</p><p><strong>${new Set(inv.map(x=>x.id)).size}</strong> IDs únicos</p><p><strong>${new Set(inv.map(x=>x.location).filter(Boolean)).size}</strong> ubicaciones</p><p><strong>${inv.filter(x=>x.formula).length}</strong> con fórmula</p>`;$('#integrityBox').textContent=JSON.stringify(runIntegrity(),null,2);}
function runIntegrity(){const ids=state.inventory.map(x=>x.id);return {ok:ids.length===111&&ids.every(validId)&&new Set(ids).size===ids.length,recordCount:ids.length,first:ids[0]||null,last:ids.at(-1)||null,uniqueIds:new Set(ids).size,duplicateIds:ids.filter((x,i)=>ids.indexOf(x)!==i),identityRule:'1 registro = 1 ID NEXUS-X'};}
function renderDiagnostics(){const settings={aiEndpoint:sessionStorage.getItem('nexus_ai_endpoint')?'configurado':'vacío',aiModel:sessionStorage.getItem('nexus_ai_model')||'vacío',apiKey:sessionStorage.getItem('nexus_ai_key')?'presente en sesión':'no configurada',web:state.web?'ON':'OFF'};$('#settingsDiag').textContent=JSON.stringify({integrity:runIntegrity(),settings},null,2)}
function toggleFavorite(id){if(state.favorites.has(id))state.favorites.delete(id);else state.favorites.add(id);localStorage.setItem('nexus_x_favorites_v1',JSON.stringify([...state.favorites]));saveActivity(`${state.favorites.has(id)?'Favorito agregado':'Favorito quitado'}: ${id}`);renderInventory();}
function saveQueryHistory(q){if(!q)return;const key='nexus_x_queries_v1';let arr=[];try{arr=JSON.parse(localStorage.getItem(key)||'[]')}catch{};arr=[q,...arr.filter(x=>x!==q)].slice(0,8);localStorage.setItem(key,JSON.stringify(arr));renderQueryHistory();}
function renderQueryHistory(){const el=$('#researchHistory');if(!el)return;let arr=[];try{arr=JSON.parse(localStorage.getItem('nexus_x_queries_v1')||'[]')}catch{};el.innerHTML=arr.length?'<div class="footer-note">Consultas recientes</div><div class="toolbar">'+arr.map(q=>`<button class="btn" data-history="${escapeHtml(q)}">${escapeHtml(q)}</button>`).join('')+'</div>':'';$$('[data-history]').forEach(b=>b.onclick=()=>{$('#researchInput').value=b.dataset.history;runResearch()});}
function updateNetworkStatus(){const el=$('#networkStatus');if(!el)return;el.classList.toggle('offline',!navigator.onLine);el.innerHTML=`<span class="status-dot"></span>${navigator.onLine?'Local · online':'Modo local · offline'}`;}
function openCommandPalette(){const items=[['⌕','Buscar en inventario','Ir a Inventario y enfocar búsqueda','inventory'],['⚗','Investigar','Abrir Investigación','research'],['⌗','Escanear QR','Abrir Escáner QR','qr'],['▤','Documentos','Abrir Documentos','documents'],['⌁','Informe','Abrir Informes','reports'],['⚙','Ajustes','Abrir Ajustes','settings']];$('#commandList').innerHTML=items.map(x=>`<button class="command-item" data-command="${x[3]}"><span><strong>${x[0]} ${x[1]}</strong><br><span class="muted">${x[2]}</span></span><span class="kbd">Enter</span></button>`).join('');$$('[data-command]').forEach(b=>b.onclick=()=>{setView(b.dataset.command);$('#commandModal').classList.remove('open');if(b.dataset.command==='inventory')setTimeout(()=>$('#inventorySearch').focus(),50)});$('#commandModal').classList.add('open');}
function renderAll(){renderDashboard();renderActivity();renderInventory();renderDiagnostics();}
async function syncRepository(){
 const status=$('#repoStatus');status.textContent='Sincronizando…';
 try{const meta=await (await fetchTimeout('https://api.github.com/repos/miqueas80/NEXUS-X-',{headers:{Accept:'application/vnd.github+json'}},WEB_TIMEOUT)).json();if(!meta.default_branch)throw new Error('Repositorio no disponible');const treeRes=await fetchTimeout(`https://api.github.com/repos/miqueas80/NEXUS-X-/git/trees/${encodeURIComponent(meta.default_branch)}?recursive=1`,{headers:{Accept:'application/vnd.github+json'}},WEB_TIMEOUT);if(!treeRes.ok)throw new Error('GitHub HTTP '+treeRes.status);const tree=await treeRes.json();const files=(tree.tree||[]).filter(x=>x.type==='blob').map(x=>x.path);state.docs=files.filter(x=>/\.(pdf|docx|xlsx|xls|csv|txt|md)$/i.test(x)).map(x=>({name:x.split('/').pop(),path:x,pages:null}));$('#documentList').innerHTML=state.docs.length?state.docs.map(d=>`<div class="result-card"><strong>${escapeHtml(d.name)}</strong><div class="muted">${escapeHtml(d.path)}</div></div>`).join(''):'<div class="notice">No hay documentos indexables.</div>';status.textContent=`OK · ${files.length} archivos`;saveActivity(`Repositorio sincronizado: ${files.length} archivos`);renderDashboard();}catch(e){console.warn(e);status.textContent='No disponible';toast('No se pudo sincronizar GitHub. NEXUS-X sigue funcionando localmente.');}
}
const CAL_KEY='nexus_x_calendar_v1';let calCursor=new Date();
function calendarEvents(){try{return JSON.parse(localStorage.getItem(CAL_KEY)||'[]')}catch{return[]}}
function saveCalendarEvents(events){localStorage.setItem(CAL_KEY,JSON.stringify(events))}
function pad2(n){return String(n).padStart(2,'0')}
function isoDate(d){return `${d.getFullYear()}-${pad2(d.getMonth()+1)}-${pad2(d.getDate())}`}
function renderCalendar(){const y=calCursor.getFullYear(),m=calCursor.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),start=(first.getDay()+6)%7;const events=calendarEvents();$('#calTitle').textContent=new Intl.DateTimeFormat('es-AR',{month:'long',year:'numeric'}).format(first).replace(/^./,c=>c.toUpperCase());const heads=['L','M','M','J','V','S','D'];let html=heads.map(x=>`<div class="dow">${x}</div>`).join('');for(let i=0;i<start;i++)html+='<div class="day muted-day"></div>';for(let d=1;d<=last.getDate();d++){const date=new Date(y,m,d),key=isoDate(date),dayEvents=events.filter(e=>e.date===key);html+=`<button type="button" class="day ${key===isoDate(new Date())?'today ':''}${dayEvents.length?'has-event':''}" data-cal-date="${key}"><span class="num">${d}</span>${dayEvents.slice(0,2).map(e=>`<span class="dot">• ${escapeHtml(e.text)}</span>`).join('')}</button>`}const total=Math.ceil((start+last.getDate())/7)*7;for(let i=start+last.getDate();i<total;i++)html+='<div class="day muted-day"></div>';$('#calGrid').innerHTML=html;$$('[data-cal-date]').forEach(b=>b.onclick=()=>{$('#calDate').value=b.dataset.calDate;$('#calEvent').focus();});const grouped=events.filter(e=>e.date>=isoDate(new Date(y,m,1))&&e.date<=isoDate(last)).sort((a,b)=>a.date.localeCompare(b.date));$('#calEvents').innerHTML=grouped.length?grouped.map((e,i)=>`<div class="calendar-event"><span><strong>${escapeHtml(e.date)}</strong> · ${escapeHtml(e.text)}</span><button class="btn danger" data-cal-delete="${i}">Eliminar</button></div>`).join(''):'Sin eventos para este mes.';$$('[data-cal-delete]').forEach((b)=>b.onclick=()=>{const target=grouped[Number(b.dataset.calDelete)];saveCalendarEvents(events.filter(e=>!(e.date===target.date&&e.text===target.text)));renderCalendar()})}
function openCalendar(){calCursor=new Date();$('#calDate').value=isoDate(calCursor);$('#calEvent').value='';$('#calendarModal').classList.add('open');renderCalendar()}
function addCalendarEvent(){const date=$('#calDate').value,text=$('#calEvent').value.trim();if(!date||!text){toast('Indicá fecha y evento.');return}const events=calendarEvents();events.push({date,text});events.sort((a,b)=>a.date.localeCompare(b.date));saveCalendarEvents(events);$('#calEvent').value='';renderCalendar();saveActivity(`Evento agregado: ${text}`);toast('Evento agregado al calendario.')}

function bind(){
 updateNetworkStatus();window.addEventListener('online',updateNetworkStatus);window.addEventListener('offline',updateNetworkStatus);$('#commandBtn').onclick=openCommandPalette;window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommandPalette()}if(e.key==='Escape')$$('.modal-backdrop.open').forEach(m=>m.classList.remove('open'))});renderQueryHistory();
 $$('.nav-btn').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$$('.research-tab').forEach(b=>b.addEventListener('click',()=>setResearchTab(b.dataset.tab)));$('#syncRepoBtn').onclick=syncRepository;
 $('#globalSearchBtn').onclick=()=>{const q=$('#globalSearch').value.trim();if(q){setView('research');$('#researchInput').value=q;runResearch()}};$('#globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter')$('#globalSearchBtn').click()});
 $('#webToggle').onclick=()=>{state.web=!state.web;$('#webToggle').textContent=`🌐 Internet: ${state.web?'ON':'OFF'}`;toast(state.web?'Búsqueda web activada.':'Búsqueda web desactivada.');if(state.web&&state.lastQuery)runWeb(state.lastQuery)};
 $('#inventorySearch').oninput=renderInventory;$('#locationFilter').onchange=renderInventory;$('#statusFilter').onchange=renderInventory;$('#newItemBtn').onclick=newItem;$('#saveItemBtn').onclick=saveItem;$('#deleteItemBtn').onclick=deleteItem;$('#exportExcelBtn').onclick=exportCsv;$('#importExcelBtn').onclick=()=>$('#excelInput').click();$('#excelInput').onchange=e=>{const f=e.target.files[0];if(f)importExcel(f);e.target.value=''};
 $('#researchBtn').onclick=runResearch;$('#researchInput').addEventListener('keydown',e=>{if(e.key==='Enter')runResearch()});$('#aiBtn').onclick=aiQuery;$('#aiInput').addEventListener('keydown',e=>{if(e.key==='Enter')aiQuery()});
 $('#startQrBtn').onclick=startQr;$('#stopQrBtn').onclick=stopQr;$('#qrImage').onchange=e=>{const f=e.target.files[0];if(f)decodeQrImage(f);e.target.value=''};$('#manualQrBtn').onclick=()=>{if($('#manualQr').value.trim())processQr($('#manualQr').value)};
 $('#loadWordBtn').onclick=()=>$('#wordInput').click();$('#wordInput').onchange=e=>{const f=e.target.files[0];if(f)importWord(f);e.target.value=''};$('#loadPdfBtn').onclick=()=>$('#pdfInput').click();$('#pdfInput').onchange=e=>{const f=e.target.files[0];if(f)importPdf(f);e.target.value=''};$('#resetMasterBtn').onclick=loadMaster;
 $('#exportReportBtn').onclick=exportReport;$('#settingsBtn').onclick=()=>setView('settings');$('#saveAiBtn').onclick=()=>{sessionStorage.setItem('nexus_ai_endpoint',$('#aiEndpoint').value.trim());sessionStorage.setItem('nexus_ai_model',$('#aiModel').value.trim());sessionStorage.setItem('nexus_ai_key',$('#aiKey').value.trim());toast('Configuración IA guardada solo en esta sesión.');renderDiagnostics()};$('#clearLocalBtn').onclick=()=>{if(confirm('¿Borrar cambios locales? Se volverá a cargar la base maestra validada.')){localStorage.removeItem(DB_KEY);loadMaster()}};
 $$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.remove('open'));$('#calendarBtn').onclick=openCalendar;$('#calPrev').onclick=()=>{calCursor.setMonth(calCursor.getMonth()-1);renderCalendar()};$('#calNext').onclick=()=>{calCursor.setMonth(calCursor.getMonth()+1);renderCalendar()};$('#calToday').onclick=()=>{calCursor=new Date();renderCalendar()};$('#calAdd').onclick=addCalendarEvent;$('#calEvent').addEventListener('keydown',e=>{if(e.key==='Enter')addCalendarEvent()});window.addEventListener('beforeunload',stopQr);
}
async function boot(){bind();$('#aiEndpoint').value=sessionStorage.getItem('nexus_ai_endpoint')||'';$('#aiModel').value=sessionStorage.getItem('nexus_ai_model')||'';renderActivity();await loadMaster();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(console.warn);}
boot();
})();
