(() => {
'use strict';
const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];
const DB_KEY='nexus_x_inventory_v1';
const DOC_DB='NEXUS_X_DOCUMENTS_V2';
const DOC_STORE='documents';
const DOC_CACHE_VERSION=2;
const DEFAULT_REPO_OWNER='miqueas80';
const DEFAULT_REPO_NAME='NEXUS-X-';
const DEFAULT_REPO_BRANCH='main';
const REPO_CONFIG_KEY='nexus_x_repo_v2';
const API_CONFIG_KEY='nexus_x_api_v2';
const DOC_MAX_BYTES=6*1024*1024;
const SETTINGS_KEY='nexus_x_settings_v1';
const WEB_TIMEOUT=6500;
const state={inventory:[],view:'dashboard',web:false,stream:null,scanBusy:false,docs:[],lastQuery:'',activity:[],favorites:new Set(JSON.parse(localStorage.getItem('nexus_x_favorites_v1')||'[]')),docIndexReady:false,docSyncing:false,repo:null,viewerDoc:null,viewerMode:'document',viewerWebContext:''};
const MASTER_URL='inventory.json';

function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function norm(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();}
function canonicalId(v){let s=String(v??'').trim(); const m=s.match(/(?:NEXUS[-_:]?X|X|NX)[-_: ]*(\d{1,6})$/i)||s.match(/^(\d{1,6})$/); return m?`NEXUS-X-${String(Number(m[1])).padStart(4,'0')}`:s;}
function validId(v){return /^NEXUS-X-\d{4}$/.test(String(v||''));}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),3200);}
function setView(name){state.view=name;$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name)); if(name==='inventory')renderInventory(); if(name==='reports')renderReports(); if(name==='settings')renderDiagnostics();}
function saveInventory(){localStorage.setItem(DB_KEY,JSON.stringify(state.inventory));}
function saveActivity(text){state.activity.unshift({text,at:new Date().toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})});state.activity=state.activity.slice(0,8);renderActivity();}

function loadApiConfig(){try{return JSON.parse(localStorage.getItem(API_CONFIG_KEY)||'{}')}catch{return {}}}
function saveApiConfig(cfg){localStorage.setItem(API_CONFIG_KEY,JSON.stringify(cfg||{}))}
function loadRepoConfig(){try{return JSON.parse(localStorage.getItem(REPO_CONFIG_KEY)||'null')}catch{return null}}
function detectGitHubRepo(){
 const saved=loadRepoConfig(); if(saved?.owner&&saved?.name)return saved;
 const host=location.hostname||''; const path=(location.pathname||'').replace(/^\//,'').split('/').filter(Boolean);
 if(host.endsWith('.github.io')){const owner=host.split('.')[0];const name=path[0]||owner+'.github.io';return {owner,name,branch:'main',detected:true}}
 return {owner:DEFAULT_REPO_OWNER,name:DEFAULT_REPO_NAME,branch:DEFAULT_REPO_BRANCH,detected:false};
}
function activeRepo(){if(!state.repo)state.repo=detectGitHubRepo();return state.repo}
function maskKey(k){return k?`${k.slice(0,4)}••••${k.slice(-4)}`:''}
function updateApiUi(){
 const cfg=loadApiConfig();
 const provider=$('#apiProvider'); if(provider)provider.value=cfg.provider||'gemini';
 const key=$('#apiKey'); if(key)key.value=cfg.key||'';
 const repo=activeRepo(); const owner=$('#repoOwner'); if(owner)owner.value=repo.owner||''; const name=$('#repoName'); if(name)name.value=repo.name||''; const branch=$('#repoBranch'); if(branch)branch.value=repo.branch||'main';
 const st=$('#apiStatus'); if(st)st.textContent=cfg.key?`API guardada localmente · ${maskKey(cfg.key)}`:'Sin API configurada';
 const rs=$('#repoConfigStatus'); if(rs)rs.textContent=`Repositorio: ${repo.owner}/${repo.name}@${repo.branch||'main'}`;
}
function saveApiSettings(){const key=$('#apiKey')?.value.trim();const provider=$('#apiProvider')?.value||'gemini';if(!key){toast('Pegá una API Key para guardar la configuración.');return}saveApiConfig({provider,key,savedAt:new Date().toISOString()});state.web=true;$('#webToggle').textContent='🌐 Internet: ON';updateApiUi();renderDiagnostics();toast('API configurada y guardada en este navegador. No se guarda en GitHub.');}
function saveRepoSettings(){const owner=$('#repoOwner')?.value.trim(),name=$('#repoName')?.value.trim(),branch=$('#repoBranch')?.value.trim()||'main';if(!owner||!name){toast('Indicá propietario y repositorio.');return}const repo={owner,name,branch,detected:false};localStorage.setItem(REPO_CONFIG_KEY,JSON.stringify(repo));state.repo=repo;updateApiUi();toast('Repositorio configurado.');syncRepository()}
function clearApiSettings(){localStorage.removeItem(API_CONFIG_KEY);state.web=false;$('#webToggle').textContent='🌐 Internet: OFF';updateApiUi();renderDiagnostics();toast('API eliminada de este navegador.');}

function openDocDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DOC_DB,DOC_CACHE_VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(DOC_STORE))db.createObjectStore(DOC_STORE,{keyPath:'path'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});}
async function putDoc(doc){try{const db=await openDocDB();await new Promise((res,rej)=>{const tx=db.transaction(DOC_STORE,'readwrite');tx.objectStore(DOC_STORE).put(doc);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close()}catch(e){console.warn('No se pudo guardar índice documental',e)}}
async function getCachedDocs(){try{const db=await openDocDB();const rows=await new Promise((res,rej)=>{const tx=db.transaction(DOC_STORE,'readonly'),req=tx.objectStore(DOC_STORE).getAll();req.onsuccess=()=>res(req.result||[]);req.onerror=()=>rej(req.error)});db.close();return rows}catch(e){console.warn('Cache documental',e);return[]}}
function docType(path){const ext=(String(path).split('.').pop()||'').toLowerCase();return ext==='docx'?'DOCX':ext==='pdf'?'PDF':ext==='xlsx'||ext==='xls'?'XLSX':ext==='csv'?'CSV':ext==='md'?'MD':ext==='txt'?'TXT':ext.toUpperCase()}
function chunkText(text,size=1100,overlap=140){const clean=String(text||'').replace(/\r/g,'').replace(/[ \t]+/g,' ').replace(/\n{3,}/g,'\n\n').trim();const out=[];if(!clean)return out;let start=0;while(start<clean.length){let end=Math.min(clean.length,start+size);if(end<clean.length){const cut=clean.lastIndexOf(' ',end);if(cut>start+500)end=cut}const value=clean.slice(start,end).trim();if(value)out.push(value);if(end>=clean.length)break;start=Math.max(end-overlap,start+1)}return out}
function entityRelations(text,doc){const nt=norm(text);const rel=[];for(const r of state.inventory){const terms=[r.id,r.name,r.formula].filter(Boolean).map(norm);const matched=terms.filter(t=>t.length>=3&&nt.includes(t));if(matched.length){const snippets=[];for(const term of matched.slice(0,3)){const pos=nt.indexOf(term);if(pos>=0)snippets.push(String(text).slice(Math.max(0,pos-180),Math.min(String(text).length,pos+420)).replace(/\s+/g,' ').trim())}rel.push({type:'document→entity',entityId:r.id,entityName:r.name,reason:'mención directa',terms:matched,snippets})}}return rel}
async function indexDocument({name,path,text,type,size=0,source='local',url='',blob=null,mime=''}){const clean=String(text||'').trim();const chunks=chunkText(clean);const relations=entityRelations(clean,{name,path});const doc={name,path:path||name,type:type||docType(name),size:Number(size||0),source,text:clean,chunks,relations,indexedAt:new Date().toISOString(),url,mime:mime||blob?.type||'',blob:blob||null};await putDoc(doc);const i=state.docs.findIndex(x=>x.path===doc.path);const meta={...doc,text:clean,chunks,relations};if(i>=0)state.docs[i]=meta;else state.docs.push(meta);state.docIndexReady=true;renderDocuments();renderDashboard();return doc}
function documentSummary(d){const relationCount=(d.relations||[]).length;return `<div class="result-card doc-card"><div style="display:flex;justify-content:space-between;gap:10px;align-items:flex-start"><div><strong>📄 ${escapeHtml(d.name)}</strong><div class="muted">${escapeHtml(d.type)} · ${d.chunks?.length||0} fragmentos · ${relationCount} conexiones · ${escapeHtml(d.source||'local')}</div></div><button class="doc-ai-circle" title="Abrir visor + IA" data-open-doc="${escapeHtml(d.path)}">AI</button></div><div>${escapeHtml(d.path||d.name)}</div>${relationCount?`<div class="footer-note">Relacionado con: ${d.relations.slice(0,6).map(r=>escapeHtml(r.entityId+' · '+r.entityName)).join(' · ')}</div>`:''}<div class="toolbar section"><button class="btn teal" data-open-doc="${escapeHtml(d.path)}">▣ Ver documento</button>${d.url?`<a class="btn" href="${escapeHtml(d.url)}" target="_blank" rel="noopener noreferrer">Abrir fuente</a>`:''}</div></div>`}
function renderDocuments(){const el=$('#documentList');if(!el)return;if(state.docSyncing)$('#repoStatus').textContent='Indexando documentos…';if(!state.docs.length){el.innerHTML='<div class="notice">Sin documentos indexados. Subí PDF, Word, Excel, CSV, TXT o Markdown al repositorio y sincronizá, o cargalos manualmente.</div>';return}el.innerHTML=`<div class="notice"><strong>${state.docs.length} documento(s) indexado(s).</strong> Abrí cualquier documento para leerlo localmente y usar su asistente AI contextual.</div>`+state.docs.map(documentSummary).join('');$$('[data-open-doc]').forEach(b=>b.onclick=()=>openDocumentViewer(b.dataset.openDoc));}
function documentSearch(q){const nq=norm(q);if(!nq)return[];const terms=nq.split(/\s+/).filter(t=>t.length>1);const out=[];for(const d of state.docs){for(let i=0;i<(d.chunks||[]).length;i++){const chunk=d.chunks[i],nc=norm(chunk);let score=0;if(nc.includes(nq))score+=55;for(const t of terms)if(nc.includes(t))score+=8;for(const rel of (d.relations||[]))if(terms.some(t=>norm(rel.entityName).includes(t)||norm(rel.entityId).includes(t)))score+=15;if(score>0)out.push({d,chunk,index:i,score})}}return out.sort((a,b)=>b.score-a.score).slice(0,16)}
function crossRelations(docHits,invHits){const map=new Map();for(const h of docHits){for(const r of h.d.relations||[]){const key=r.entityId;map.set(key,(map.get(key)||0)+1)}}for(const h of invHits){const key=h.r.id;map.set(key,(map.get(key)||0)+2)}return [...map.entries()].sort((a,b)=>b[1]-a[1]).map(([id,score])=>({id,score,r:state.inventory.find(x=>x.id===id)})).filter(x=>x.r)}
async function indexLocalFile(file){const type=docType(file.name);if(file.size>DOC_MAX_BYTES)throw new Error(`Archivo demasiado grande (${Math.round(file.size/1048576)} MB). Límite ${DOC_MAX_BYTES/1048576} MB por documento.`);if(type==='PDF')return indexPdfDocument(file);if(type==='DOCX')return indexDocxDocument(file);if(['XLSX','CSV'].includes(type))return indexSpreadsheetDocument(file);const text=await file.text();return indexDocument({name:file.name,path:'local:'+file.name,type,size:file.size,text,source:'archivo local',blob:file,mime:file.type})}
async function indexDocxDocument(file){await loadScript('https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js','JSZip');const zip=await JSZip.loadAsync(await file.arrayBuffer());const xml=await zip.file('word/document.xml').async('text');const doc=new DOMParser().parseFromString(xml,'application/xml');const text=[...doc.getElementsByTagName('w:p')].map(p=>[...p.getElementsByTagName('w:t')].map(t=>t.textContent||'').join('').trim()).filter(Boolean).join('\n');return indexDocument({name:file.name,path:'local:'+file.name,type:'DOCX',size:file.size,text,source:'archivo local',blob:file,mime:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'})}
async function indexPdfDocument(file){await loadScript('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js','pdfjsLib');const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;const pages=[];for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n),content=await page.getTextContent();pages.push(`PÁGINA ${n}\n`+content.items.map(x=>x.str||'').join(' '))}return indexDocument({name:file.name,path:'local:'+file.name,type:'PDF',size:file.size,text:pages.join('\n\n'),source:'archivo local',blob:file,mime:'application/pdf'})}
async function indexSpreadsheetDocument(file){await loadScript('https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js','XLSX');const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true,raw:false,defval:''});const sheets=wb.SheetNames.map(name=>`HOJA: ${name}\n`+XLSX.utils.sheet_to_csv(wb.Sheets[name])).join('\n\n');return indexDocument({name:file.name,path:'local:'+file.name,type:docType(file.name),size:file.size,text:sheets,source:'archivo local',blob:file,mime:file.type})}
async function loadCachedDocumentIndex(){state.docs=await getCachedDocs();state.docIndexReady=state.docs.length>0;renderDocuments();renderDashboard()}
function validateInventory(records, expected=111){
 if(!Array.isArray(records)||!records.length)throw new Error('La base no contiene registros.');
 const ids=records.map(x=>x.id); const dup=ids.filter((x,i)=>ids.indexOf(x)!==i); if(dup.length)throw new Error(`IDs duplicados: ${[...new Set(dup)].join(', ')}`);
 const bad=records.filter(x=>!validId(x.id)); if(bad.length)throw new Error(`Hay ${bad.length} IDs con formato inválido.`);
 if(expected!==null && records.length!==expected)throw new Error(`Se esperaban ${expected} registros y llegaron ${records.length}.`);
 return true;
}
function normalizeRecord(r, fallbackIndex){
 const id=canonicalId(r.id||r.ID_NEXUS_X||r.codigo||r.ID||'');
 return {id,record:Number(r.record||fallbackIndex||0),originalNumber:String(r.originalNumber??r.Nº_Original??''),name:String(r.name??r.Sustancia_Mezcla_Material??r.nombre??''),formula:String(r.formula??r.Formula??''),physicalState:String(r.physicalState??r.Estado_Fisico??''),presentation:String(r.presentation??r.Presentacion??''),originalPackage:String(r.originalPackage??r.Envase_Original??''),expiry:String(r.expiry??r.Fecha_Envasado_Vencimiento??''),location:String(r.location??r.Ubicacion_Armario??''),notes:String(r.notes??r.Observaciones??''),source:String(r.source??'')};
}
async function loadMaster(){
 try{const res=await fetch(MASTER_URL,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();const recs=data.records.map(normalizeRecord);validateInventory(recs,111);state.inventory=recs;saveInventory();saveActivity('Base maestra JSON cargada y validada');}
 catch(e){console.warn('Master JSON',e);try{const cached=JSON.parse(localStorage.getItem(DB_KEY)||'null');validateInventory(cached,111);state.inventory=cached;saveActivity('Base local recuperada');}catch(_){state.inventory=[];saveActivity('No se pudo cargar la base maestra');}}
 renderAll();
}
function renderDashboard(){
 const inv=state.inventory;$('#statInventory').textContent=inv.length;$('#statLocations').textContent=new Set(inv.map(x=>x.location).filter(Boolean)).size;$('#statFormula').textContent=inv.filter(x=>x.formula).length;$('#taskFormula').textContent=inv.filter(x=>!x.formula).length;$('#taskLocation').textContent=inv.filter(x=>!x.location).length;$('#taskDocs').textContent=state.docs.length;$('#legendKnown').textContent=inv.length;$('#statSystem').textContent=validId(inv[0]?.id||'NEXUS-X-0000')?'OK':'REVISAR';}
function renderActivity(){const el=$('#activity');el.innerHTML=state.activity.length?state.activity.map(a=>`<div class="activity"><span>●</span><span>${escapeHtml(a.text)}</span><span class="time">${a.at}</span></div>`).join(''):'<div class="empty">Sin actividad todavía.</div>';}
function inventoryStatus(r){const s=norm(r.expiry);if(!s||s.includes('no presenta')||s.includes('desconoce'))return ['ok','SIN VENCIMIENTO']; const d=new Date(r.expiry);if(Number.isNaN(d.getTime()))return ['warn','REVISAR FECHA'];const days=Math.ceil((d-new Date())/86400000);return days<0?['danger','VENCIDO']:days<=30?['danger',`URGENTE · ${days} d`]:days<=90?['warn',`PRÓXIMO · ${days} d`]:['ok',`VIGENTE · ${days} d`];}
function filteredInventory(){const q=norm($('#inventorySearch')?.value||'');const loc=$('#locationFilter')?.value||'';const status=$('#statusFilter')?.value||'';return state.inventory.filter(r=>{const st=inventoryStatus(r)[0];return (!loc||r.location===loc)&&(!status||st===status)&&(!q||norm(Object.values(r).join(' ')).includes(q));});}
function renderInventory(){const locs=[...new Set(state.inventory.map(x=>x.location).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));const sel=$('#locationFilter');if(sel){const cur=sel.value;sel.innerHTML='<option value="">Todas las ubicaciones</option>'+locs.map(x=>`<option>${escapeHtml(x)}</option>`).join('');if(locs.includes(cur))sel.value=cur;}const sf=$('#statusFilter');const statusCur=sf?.value||'';if(sf)sf.value=statusCur;const rows=filteredInventory();$('#inventorySummary').textContent=`Mostrando ${rows.length} de ${state.inventory.length} registros.`;const counts={ok:0,warn:0,danger:0};state.inventory.forEach(r=>counts[inventoryStatus(r)[0]]++);const quick=$('#inventoryQuick');if(quick)quick.innerHTML=`<button class="btn" data-qfilter="">Todos · ${state.inventory.length}</button><button class="btn teal" data-qfilter="ok">Vigentes · ${counts.ok}</button><button class="btn" data-qfilter="warn">Revisar · ${counts.warn}</button><button class="btn danger" data-qfilter="danger">Alertas · ${counts.danger}</button>`;const table=$('#inventoryTable');table.innerHTML=rows.length?`<table><thead><tr><th>ID</th><th>Sustancia / material</th><th>Fórmula</th><th>Estado</th><th>Presentación</th><th>Ubicación</th><th>Vencimiento</th><th></th></tr></thead><tbody>${rows.map(r=>{const st=inventoryStatus(r);const fav=state.favorites.has(r.id);return `<tr><td class="id">${escapeHtml(r.id)}</td><td><strong>${escapeHtml(r.name)}</strong><br><span class="muted">Original: ${escapeHtml(r.originalNumber)}</span></td><td>${escapeHtml(r.formula||'—')}</td><td>${escapeHtml(r.physicalState||'—')}</td><td>${escapeHtml(r.presentation||'—')}</td><td>${escapeHtml(r.location||'—')}</td><td><span class="badge ${st[0]}">${escapeHtml(st[1])}</span></td><td><div class="row-actions"><button class="favorite-btn ${fav?'active':''}" title="${fav?'Quitar de favoritos':'Agregar a favoritos'}" data-fav="${escapeHtml(r.id)}">${fav?'★':'☆'}</button><button class="btn" data-edit="${escapeHtml(r.id)}">Abrir</button></div></td></tr>`}).join('')}</tbody></table>`:'<div class="empty">No hay coincidencias.</div>';$$('[data-edit]').forEach(b=>b.addEventListener('click',()=>openItem(b.dataset.edit)));$$('[data-fav]').forEach(b=>b.addEventListener('click',()=>toggleFavorite(b.dataset.fav)));$$('[data-qfilter]').forEach(b=>b.addEventListener('click',()=>{$('#statusFilter').value=b.dataset.qfilter;renderInventory()}));}
function openItem(id){const r=state.inventory.find(x=>x.id===id);if(!r)return;$('#itemModalTitle').textContent=r.id;$('#fId').value=r.id;$('#fOriginal').value=r.originalNumber;$('#fName').value=r.name;$('#fFormula').value=r.formula;$('#fState').value=r.physicalState;$('#fPresentation').value=r.presentation;$('#fPackage').value=r.originalPackage;$('#fExpiry').value=r.expiry;$('#fLocation').value=r.location;$('#fNotes').value=r.notes;$('#deleteItemBtn').style.display='inline-block';$('#itemModal').classList.add('open');}
function newItem(){['fId','fOriginal','fName','fFormula','fState','fPresentation','fPackage','fExpiry','fLocation','fNotes'].forEach(id=>$('#'+id).value='');$('#fId').value=nextId();$('#deleteItemBtn').style.display='none';$('#itemModalTitle').textContent='Nuevo registro';$('#itemModal').classList.add('open');}
function nextId(){let max=0;for(const r of state.inventory){const m=r.id.match(/(\d{4})$/);if(m)max=Math.max(max,Number(m[1]));}return `NEXUS-X-${String(max+1).padStart(4,'0')}`;}
function saveItem(){const r=normalizeRecord({id:$('#fId').value,originalNumber:$('#fOriginal').value,name:$('#fName').value,formula:$('#fFormula').value,physicalState:$('#fState').value,presentation:$('#fPresentation').value,originalPackage:$('#fPackage').value,expiry:$('#fExpiry').value,location:$('#fLocation').value,notes:$('#fNotes').value},state.inventory.length+1);if(!validId(r.id)||!r.name){toast('ID NEXUS-X válido y nombre son obligatorios.');return}const idx=state.inventory.findIndex(x=>x.id===r.id);if(idx>=0)state.inventory[idx]=r;else{if(state.inventory.some(x=>x.id===r.id)){toast('Ese ID ya existe.');return}state.inventory.push(r)}saveInventory();saveActivity(`${idx>=0?'Registro actualizado':'Registro creado'}: ${r.id}`);$('#itemModal').classList.remove('open');renderAll();}
function deleteItem(){const id=$('#fId').value;if(!confirm(`¿Eliminar ${id}?`))return;state.inventory=state.inventory.filter(x=>x.id!==id);saveInventory();saveActivity(`Registro eliminado: ${id}`);$('#itemModal').classList.remove('open');renderAll();}
function searchLocal(q){const nq=norm(q);if(!nq)return[];return state.inventory.map(r=>{const hay=norm(Object.values(r).join(' '));let score=0;if(norm(r.id)===nq)score+=100;if(norm(r.name).includes(nq))score+=45;if(r.formula&&norm(r.formula).includes(nq))score+=35;if(norm(r.location).includes(nq))score+=20;if(hay.includes(nq))score+=10;return {r,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,12);}
function renderResearchLabs(hits,q,docHits=[],links=[]){
 const evidence=$('#evidenceLab'),claims=$('#claimsLab'),graph=$('#graphLab'),audit=$('#auditLab');
 [evidence,claims,graph,audit].forEach(x=>x.innerHTML='');
 evidence.innerHTML='<h3>Laboratorio de evidencia</h3>'+(hits.length?hits.slice(0,6).map(({r,score})=>`<div class="result-card"><strong>${escapeHtml(r.id)} · ${escapeHtml(r.name)}</strong><div class="muted">Registro local · score ${score}</div><div>${escapeHtml(r.formula||'Sin fórmula')} · ${escapeHtml(r.location||'Ubicación no informada')}</div><div class="footer-note">Fuente: ${escapeHtml(r.source||'inventory.json')}</div></div>`).join(''):'<div class="notice">Sin coincidencias directas en el inventario.</div>')+(docHits.length?docHits.slice(0,8).map(h=>`<div class="result-card"><strong>📄 ${escapeHtml(h.d.name)} · fragmento ${h.index+1}</strong><div class="muted">Evidencia documental · score ${h.score}</div><div>${escapeHtml(h.chunk.slice(0,650))}${h.chunk.length>650?'…':''}</div><div class="footer-note">${(h.d.relations||[]).filter(r=>norm(h.chunk).includes(norm(r.entityName))||norm(h.chunk).includes(norm(r.entityId))).slice(0,4).map(r=>escapeHtml(r.entityId+' · '+r.entityName)).join(' · ')}</div></div>`).join(''):'');
 const claimRows=[];hits.slice(0,8).forEach(({r})=>{claimRows.push([`${r.id} corresponde a ${r.name}`,'directa',r.id]);if(r.location)claimRows.push([`${r.name} está ubicado en ${r.location}`,'directa',r.id]);if(r.formula)claimRows.push([`${r.name} tiene fórmula ${r.formula}`,'directa',r.id]);});docHits.slice(0,8).forEach(h=>claimRows.push([`${h.d.name} contiene evidencia relacionada con la consulta`,'documental',`${h.d.name} · fragmento ${h.index+1}`]));
 claims.innerHTML='<h3>Claims</h3>'+claimRows.map(c=>`<div class="result-card"><strong>${escapeHtml(c[0])}</strong><div class="muted">Tipo: ${escapeHtml(c[1])} · evidencia: ${escapeHtml(c[2])}</div></div>`).join('');
 const nodes=[],edges=[];const add=(id,label,type)=>{if(!nodes.some(n=>n.id===id))nodes.push({id,label,type})};hits.slice(0,6).forEach(({r})=>{add('i:'+r.id,r.id,'material');add('n:'+r.name,r.name,'entidad');edges.push(['i:'+r.id,'n:'+r.name,'identidad']);if(r.formula){add('f:'+r.formula,r.formula,'formula');edges.push(['i:'+r.id,'f:'+r.formula,'formula'])}if(r.location){add('l:'+r.location,r.location,'ubicación');edges.push(['i:'+r.id,'l:'+r.location,'ubicación'])}});docHits.slice(0,8).forEach(h=>{const did='d:'+h.d.path;add(did,h.d.name,'documento');for(const rel of (h.d.relations||[]).filter(rel=>links.some(x=>x.id===rel.entityId)).slice(0,5)){add('i:'+rel.entityId,rel.entityId,'material');edges.push([did,'i:'+rel.entityId,'mención/evidencia'])}});
 graph.innerHTML='<h3>Grafo NEXUS-X</h3><div class="notice">'+nodes.length+' nodos · '+edges.length+' relaciones · documentos conectados: '+docHits.length+'</div><div class="section" style="display:flex;flex-wrap:wrap;gap:8px">'+nodes.map(n=>`<span class="badge">${escapeHtml(n.type)}: ${escapeHtml(n.label)}</span>`).join('')+'</div><div class="footer-note">'+edges.map(e=>`${escapeHtml(e[0].slice(2))} → ${escapeHtml(e[2])} → ${escapeHtml(e[1].slice(2))}`).join('<br>')+'</div>';
 audit.innerHTML='<h3>Auditoría</h3><div class="diagnostic">'+escapeHtml(JSON.stringify({query:q,localFirst:true,inventoryHits:hits.length,documentHits:docHits.length,connectedEntities:links.map(x=>x.id),documentsIndexed:state.docs.length,webEnabled:state.web,adversarial:$('#adversarial').checked,steps:['normalización','búsqueda de entidades','búsqueda documental','cruce de relaciones','separación de evidencia','web opcional'],timestamp:new Date().toISOString()},null,2))+'</div>';
}
function setResearchTab(tab){$$('.research-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));['evidenceLab','claimsLab','graphLab','auditLab'].forEach(id=>$('#'+id).style.display='none');if(tab==='evidence')$('#evidenceLab').style.display='block';if(tab==='claims')$('#claimsLab').style.display='block';if(tab==='graph')$('#graphLab').style.display='block';if(tab==='audit')$('#auditLab').style.display='block';if(tab==='answer')$('#researchResults').style.display='block';else $('#researchResults').style.display='none';}
function runResearch(){const q=$('#researchInput').value.trim();if(!q){toast('Escribí una consulta.');return}state.lastQuery=q;saveQueryHistory(q);const hits=searchLocal(q),docHits=documentSearch(q),links=crossRelations(docHits,hits);$('#researchLocal').innerHTML=(hits.length||docHits.length)?`<strong>${hits.length} entidad(es) · ${docHits.length} evidencia(s) documental(es).</strong> NEXUS-X cruza inventario y archivos locales antes de Internet.`:'No hay coincidencias locales en inventario ni documentos indexados. Podés activar Internet si necesitás contexto externo.';$('#researchResults').innerHTML=hits.map(({r,score})=>`<div class="result-card"><strong>${escapeHtml(r.name)} <span class="id">${escapeHtml(r.id)}</span></strong><div class="muted">${escapeHtml(r.formula||'Sin fórmula')} · ${escapeHtml(r.physicalState||'—')} · ${escapeHtml(r.location||'—')}</div><div class="footer-note">Puntaje local: ${score}</div><button class="btn section" data-result-id="${escapeHtml(r.id)}">Ver ficha</button></div>`).join('')+(docHits.length?`<h3 class="section">Evidencia documental</h3>`+docHits.slice(0,8).map(h=>`<div class="result-card"><strong>📄 ${escapeHtml(h.d.name)}</strong><div class="muted">${escapeHtml(h.d.type)} · fragmento ${h.index+1}</div><div>${escapeHtml(h.chunk.slice(0,700))}${h.chunk.length>700?'…':''}</div><div class="footer-note">${h.d.relations?.filter(r=>links.some(x=>x.id===r.entityId)).slice(0,5).map(r=>escapeHtml(r.entityId+' · '+r.entityName)).join(' · ')||'Sin entidad directa detectada'}</div></div>`).join(''):'');$$('[data-result-id]').forEach(b=>b.addEventListener('click',()=>openItem(b.dataset.resultId)));renderResearchLabs(hits,q,docHits,links);setResearchTab('answer');if(state.web)runWeb(q);else $('#webResults').innerHTML='';$('#chat').innerHTML=`<div class="msg bot">Contexto local preparado: ${hits.length} entidad(es) y ${docHits.length} fragmento(s) documental(es). Las respuestas deben distinguir evidencia, inferencia y contexto externo.</div>`;}
async function fetchTimeout(url,options={},ms=WEB_TIMEOUT){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...options,signal:c.signal})}finally{clearTimeout(t)}}
function extractGeminiText(data){
 if(data?.output_text)return String(data.output_text);
 const parts=[];
 for(const step of (data?.steps||[])) for(const block of (step?.content||[])) if(block?.type==='text'&&block.text)parts.push(block.text);
 if(parts.length)return parts.join('\n');
 for(const item of (data?.output||[])){if(item?.text)parts.push(item.text);for(const c of (item?.content||[]))if(c?.text)parts.push(c.text)}
 if(parts.length)return parts.join('\n');
 const candidates=data?.candidates||[];return candidates.map(c=>(c?.content?.parts||[]).map(p=>p.text||'').join('')).filter(Boolean).join('\n');
}
function extractGeminiCitations(data){
 const out=[]; const seen=new Set();
 const add=(title,url)=>{if(url&&!seen.has(url)){seen.add(url);out.push({title:title||url,url})}};
 for(const step of (data?.steps||[])) for(const block of (step?.content||[])) for(const a of (block?.annotations||[])) if(a?.type==='url_citation')add(a.title,a.url);
 const gm=data?.groundingMetadata||data?.candidates?.[0]?.groundingMetadata; for(const c of (gm?.groundingChunks||[])) if(c?.web)add(c.web.title,c.web.uri);
 return out;
}
async function geminiRequest(input,{web=false}={}){
 const cfg=loadApiConfig(); if((cfg.provider||'gemini')!=='gemini'||!cfg.key)throw new Error('Configurá una API Key de Gemini en Ajustes.');
 const model='gemini-3.8-flash';
 const url='https://generativelanguage.googleapis.com/v1beta/interactions';
 const body={model,input,tools:web?[{type:'google_search'}]:[]};
 const res=await fetchTimeout(url,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':cfg.key},body:JSON.stringify(body)},20000);
 if(!res.ok){let msg='HTTP '+res.status;try{const e=await res.json();msg=e?.error?.message||msg}catch{}throw new Error(msg)}
 return res.json();
}
async function directWebSearch(q){
 const urls=[
  `https://api.duckduckgo.com/?q=${encodeURIComponent(q)}&format=json&no_html=1&skip_disambig=1`,
  `https://r.jina.ai/http://www.google.com/search?q=${encodeURIComponent(q)}`
 ];
 for(const u of urls){try{const res=await fetchTimeout(u,{headers:{Accept:'application/json,text/plain,*/*'},cache:'no-store'},9000);if(!res.ok)continue;const ct=res.headers.get('content-type')||'';const raw=await res.text();if(ct.includes('json')||raw.trim().startsWith('{')){const d=JSON.parse(raw);const items=[];if(d.AbstractText)items.push({title:d.Heading||'Resumen',url:d.AbstractURL||'',text:d.AbstractText});for(const x of (d.RelatedTopics||[])){if(x.Text)items.push({title:x.Text.slice(0,90),url:x.FirstURL||'',text:x.Text});for(const y of (x.Topics||[]))if(y.Text)items.push({title:y.Text.slice(0,90),url:y.FirstURL||'',text:y.Text});}if(items.length)return items.slice(0,8)}else{const links=[...raw.matchAll(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g)].slice(0,8).map(m=>({title:m[1],url:m[2],text:m[1]}));if(links.length)return links}}catch(e){console.warn('web fallback',u,e)}}return[]
}
async function runWeb(q){
 const box=$('#webResults'); const cfg=loadApiConfig();
 if(!navigator.onLine){box.innerHTML='<div class="notice warn">Sin conexión a Internet. La búsqueda local y documental sigue disponible.</div>';return}
 box.innerHTML='<div class="notice">🌐 Consultando Internet…</div>';
 if(cfg.key){try{const data=await geminiRequest(`Investigá en Internet la consulta siguiente. Devolvé una síntesis breve en español y usá fuentes verificables. Consulta: ${q}`,{web:true});const text=extractGeminiText(data);const citations=extractGeminiCitations(data);box.innerHTML=`<div class="notice"><strong>🌐 Internet conectado · Google Search</strong></div><div class="result-card"><div>${escapeHtml(text||'Sin respuesta')}</div>${citations.length?'<div class="footer-note">Fuentes</div>'+citations.slice(0,10).map(c=>`<div><a href="${escapeHtml(c.url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(c.title)}</a></div>`).join(''):''}</div>`;return}catch(e){console.warn('Gemini Search no disponible',e);box.innerHTML=`<div class="notice warn">Gemini no pudo usar Google Search (${escapeHtml(e.message)}). Intentando búsqueda web alternativa…</div>`}}
 const items=await directWebSearch(q);if(!items.length){box.innerHTML='<div class="notice warn">No se pudo consultar una fuente web en este momento. La búsqueda local y documental sigue disponible.</div>';return}
 box.innerHTML=`<div class="notice"><strong>🌐 Internet conectado · búsqueda web alternativa</strong></div>`+items.map(x=>`<div class="result-card"><strong>${escapeHtml(x.title)}</strong><div>${escapeHtml(x.text||'')}</div>${x.url?`<div class="footer-note"><a href="${escapeHtml(x.url)}" target="_blank" rel="noopener noreferrer">Abrir fuente</a></div>`:''}</div>`).join('');
}

async function loadScript(url,globalName){if(window[globalName])return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=url;s.onload=resolve;s.onerror=()=>reject(new Error('No se pudo cargar '+url));document.head.appendChild(s)})}
async function importExcel(file){try{await loadScript('https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js','XLSX');const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true,raw:false,defval:''});const rows=[];for(const name of wb.SheetNames){const data=XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:''});if(!data.length)continue;let hi=0,best=-1;data.slice(0,12).forEach((row,i)=>{const s=row.map(norm).join(' ');const score=row.filter(Boolean).length+(/(id|codigo|nombre|material|sustancia|formula|ubicacion|stock)/.test(s)?8:0);if(score>best){best=score;hi=i}});const headers=data[hi].map((x,i)=>String(x||`Campo ${i+1}`).trim());for(let i=hi+1;i<data.length;i++){const raw={};headers.forEach((h,j)=>raw[h]=data[i][j]??'');if(Object.values(raw).some(v=>String(v).trim()))rows.push(raw)}}if(!rows.length)throw new Error('No se encontraron filas.');const mapped=rows.map((r,i)=>{const keys=Object.keys(r);const pick=(...names)=>{const k=keys.find(k=>names.includes(norm(k)));return k?r[k]:''};return normalizeRecord({id:pick('id nexus x','id_nexus_x','id','codigo nexus','codigo'),originalNumber:pick('nº original','n° original','numero original','nro original'),name:pick('sustancia mezcla material','sustancia','mezcla','material','nombre','descripcion'),formula:pick('formula','fórmula','formula quimica','fórmula química'),physicalState:pick('estado fisico','estado físico'),presentation:pick('presentacion','presentación'),originalPackage:pick('envase original'),expiry:pick('fecha envasado vencimiento','vencimiento','fecha vencimiento'),location:pick('ubicacion armario','ubicación armario','ubicacion','ubicación','estante'),notes:pick('observaciones','notas','comments')},i+1)});let generated=0;const used=new Set(mapped.filter(r=>validId(r.id)).map(r=>r.id));let next=1;mapped.forEach(r=>{if(!validId(r.id)){while(used.has(`NEXUS-X-${String(next).padStart(4,'0')}`))next++;r.id=`NEXUS-X-${String(next).padStart(4,'0')}`;used.add(r.id);next++;generated++}});validateInventory(mapped,null);state.inventory=mapped;saveInventory();saveActivity(`Excel importado: ${mapped.length} filas · ${generated} IDs normalizados`);renderAll();toast(`Excel cargado: ${mapped.length} registros.`)}catch(e){console.error(e);toast('No se importó el Excel: '+e.message)}}
async function importWord(file){try{await loadScript('https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js','JSZip');const zip=await JSZip.loadAsync(await file.arrayBuffer());const xml=await zip.file('word/document.xml').async('text');const doc=new DOMParser().parseFromString(xml,'application/xml');const texts=[...doc.getElementsByTagName('w:p')].map(p=>[...p.getElementsByTagName('w:t')].map(t=>t.textContent||'').join('').trim()).filter(Boolean);const text=texts.join('\n');const blocks=text.split(/(?=REGISTRO\s+\d+)/).slice(1);const labels=['ID_NEXUS_X','Nº_Original','Sustancia_Mezcla_Material','Formula','Estado_Fisico','Presentacion','Envase_Original','Fecha_Envasado_Vencimiento','Ubicacion_Armario'];const re=new RegExp('('+labels.map(x=>x.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')).join('|')+')\\s*:\\s*([\\s\\S]*?)(?=\\s+(?:'+labels.join('|')+')\\s*:|$)','g');const records=[];for(const b of blocks){const mm=b.match(/^REGISTRO\s+(\d+)/);if(!mm)continue;const o={record:Number(mm[1])};let m;while((m=re.exec(b))){o[m[1]]=(m[2]||'').replace(/\s+/g,' ').trim()}re.lastIndex=0;records.push(normalizeRecord(o,records.length+1))}validateInventory(records,111);state.inventory=records;saveInventory();await indexDocxDocument(file);saveActivity('Word maestro cargado, validado e indexado atómicamente');renderAll();toast('Word maestro validado e indexado: 111 registros.')}catch(e){console.error(e);toast('Word rechazado; se conservó la base anterior. '+e.message)}}
function qrExtractId(raw){const text=String(raw??'').trim();const m=text.match(/(?:NEXUS[-_:]?X|NX)[-_: ]*(\d{1,6})/i);return m?`NEXUS-X-${String(Number(m[1])).padStart(4,'0')}`:canonicalId(text.replace(/[?#].*$/,'').replace(/\/+$/,''));}
async function loadQrFallback(){await loadScript('https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.js','jsQR');}
async function decodeQrImage(file){try{if('BarcodeDetector' in window){const bitmap=await createImageBitmap(file);const detector=new BarcodeDetector({formats:['qr_code']});const codes=await detector.detect(bitmap);bitmap.close();if(codes[0]?.rawValue){processQr(codes[0].rawValue);return}}await loadQrFallback();const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');const scale=Math.min(1,1280/Math.max(bitmap.width,bitmap.height));canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const img=ctx.getImageData(0,0,canvas.width,canvas.height);const code=window.jsQR(img.data,img.width,img.height,{inversionAttempts:'attemptBoth'});if(!code?.data)throw new Error('No se detectó un QR en la imagen.');processQr(code.data)}catch(e){console.error(e);toast('No se pudo leer el QR: '+e.message)}}
async function startQr(){if(!navigator.mediaDevices?.getUserMedia){toast('La cámara no está disponible en este navegador/contexto. Usá HTTPS o carga un ID manual.');return}stopQr();try{state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});const v=$('#qrVideo');v.srcObject=state.stream;await v.play();$('#qrStage').classList.remove('black');$('#qrStageText').textContent='Buscando código…';if('BarcodeDetector' in window){const detector=new BarcodeDetector({formats:['qr_code']});state.scanBusy=false;const loop=async()=>{if(!state.stream||state.scanBusy)return;try{const codes=await detector.detect(v);if(codes[0]?.rawValue){state.scanBusy=true;processQr(codes[0].rawValue);return}}catch(e){}requestAnimationFrame(loop)};requestAnimationFrame(loop)}else{try{await loadQrFallback();}catch(e){$('#qrStageText').textContent='Escáner automático no disponible. Usá imagen o ID manual.';return}const canvas=document.createElement('canvas');const ctx=canvas.getContext('2d',{willReadFrequently:true});state.scanBusy=false;const loop=()=>{if(!state.stream||state.scanBusy)return;try{if(v.readyState>=2){canvas.width=v.videoWidth||640;canvas.height=v.videoHeight||480;ctx.drawImage(v,0,0,canvas.width,canvas.height);const img=ctx.getImageData(0,0,canvas.width,canvas.height);const code=window.jsQR(img.data,img.width,img.height,{inversionAttempts:'attemptBoth'});if(code?.data){state.scanBusy=true;processQr(code.data);return}}}catch(e){}requestAnimationFrame(loop)};requestAnimationFrame(loop)}}catch(e){console.error(e);toast('No se pudo iniciar la cámara: '+e.message)}}
function stopQr(){if(state.stream){state.stream.getTracks().forEach(t=>t.stop());state.stream=null}state.scanBusy=false;const v=$('#qrVideo');if(v)v.srcObject=null;$('#qrStage')?.classList.add('black');if($('#qrStageText'))$('#qrStageText').textContent='Cámara detenida'}
function processQr(raw){const id=qrExtractId(raw);const r=state.inventory.find(x=>x.id===id);stopQr();$('#qrStage').classList.add('black');if(r){$('#qrResult').innerHTML=`<div class="notice"><strong>${escapeHtml(r.id)}</strong><br>${escapeHtml(r.name)}<br><span class="muted">${escapeHtml(r.formula||'Sin fórmula')} · ${escapeHtml(r.location||'Sin ubicación')}</span></div><button class="btn primary section" id="qrOpenResult">Abrir ficha</button>`;$('#qrOpenResult').onclick=()=>openItem(r.id);saveActivity(`QR leído: ${r.id}`)}else $('#qrResult').innerHTML=`<div class="notice warn">Código detectado: <strong>${escapeHtml(id||raw)}</strong><br>No existe un registro con ese ID.</div>`;}
async function importPdf(file){try{const d=await indexPdfDocument(file);saveActivity(`PDF indexado: ${file.name} · ${d.chunks.length} fragmentos`);toast(`PDF indexado: ${d.chunks.length} fragmentos.`)}catch(e){console.error(e);toast('No se pudo indexar el PDF: '+e.message)}}
async function importDocumentFile(file){try{const d=await indexLocalFile(file);saveActivity(`Documento indexado: ${file.name} · ${d.chunks.length} fragmentos`);toast(`Documento indexado y conectado: ${file.name}`)}catch(e){console.error(e);toast('No se pudo indexar el documento: '+e.message)}}
function getDoc(path){return state.docs.find(d=>d.path===path)||null}
function docMime(d){return d?.mime||({'PDF':'application/pdf','DOCX':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','XLSX':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','XLS':'application/vnd.ms-excel','CSV':'text/csv','TXT':'text/plain','MD':'text/markdown'}[d?.type]||'application/octet-stream')}
function documentContext(d){return `DOCUMENTO: ${d.name}\nTIPO: ${d.type}\nORIGEN: ${d.source||'local'}\nRUTA: ${d.path}\nCONTENIDO:\n${String(d.text||'').slice(0,90000)}`}
function openDocumentViewer(path){const d=getDoc(path);if(!d){toast('Documento no encontrado en el índice.');return}state.viewerDoc=d;state.viewerWebContext='';$('#viewerTitle').textContent=d.name;$('#viewerMeta').textContent=`${d.type} · ${d.source||'local'} · ${d.chunks?.length||0} fragmentos`;$('[data-viewer-tab="document"]').classList.add('active');$('[data-viewer-tab="ai"]').classList.remove('active');$('#viewerDocumentPane').style.display='block';$('#viewerAiPane').style.display='none';renderDocumentViewerContent(d);$('#documentViewerModal').classList.add('open')}
async function renderDocumentViewerContent(d){const pane=$('#viewerDocumentPane');pane.innerHTML='<div class="notice">Cargando visor local…</div>';try{if(d.type==='PDF'&&d.blob){const u=URL.createObjectURL(d.blob);pane.innerHTML=`<iframe class="document-frame" src="${u}#toolbar=1&navpanes=0" title="${escapeHtml(d.name)}"></iframe><div class="footer-note">El PDF se muestra directamente desde el navegador; no depende de un visor web externo.</div>`;pane.dataset.objectUrl=u;return}if((d.type==='XLSX'||d.type==='XLS')&&d.blob){await loadScript('https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js','XLSX');const wb=XLSX.read(await d.blob.arrayBuffer(),{type:'array',cellDates:true,raw:false,defval:''});pane.innerHTML=wb.SheetNames.map(name=>`<div class="section"><h3>${escapeHtml(name)}</h3><div class="table-wrap">${XLSX.utils.sheet_to_html(wb.Sheets[name],{editable:false})}</div></div>`).join('');return}pane.innerHTML=`<div class="document-text">${escapeHtml(d.text||'Sin texto extraíble.').replace(/\n/g,'<br>')}</div>`}catch(e){pane.innerHTML=`<div class="notice warn">No se pudo mostrar el documento en modo visual: ${escapeHtml(e.message)}. El contenido indexado sigue disponible.</div><div class="document-text">${escapeHtml(d.text||'')}</div>`}}
function closeDocumentViewer(){const u=$('#viewerDocumentPane')?.dataset.objectUrl;if(u){URL.revokeObjectURL(u);$('#viewerDocumentPane').dataset.objectUrl=''}state.viewerDoc=null;$('#documentViewerModal').classList.remove('open')}
function openDocumentAI(){if(!state.viewerDoc)return;$('[data-viewer-tab="document"]').classList.remove('active');$('[data-viewer-tab="ai"]').classList.add('active');$('#viewerDocumentPane').style.display='none';$('#viewerAiPane').style.display='block';$('#viewerAiChat').innerHTML='<div class="msg bot">Soy el asistente de este documento. Primero responderé usando únicamente su contenido. Si preguntás si algo está actualizado, puedo consultar Internet y separar claramente lo que dice el documento de lo que encontré afuera.</div>';$('#viewerAiInput').focus()}
async function blobToBase64(blob){const buf=await blob.arrayBuffer();let binary='';const bytes=new Uint8Array(buf);const step=0x8000;for(let i=0;i<bytes.length;i+=step)binary+=String.fromCharCode(...bytes.subarray(i,Math.min(i+step,bytes.length)));return btoa(binary)}
async function viewerAiAsk(){const d=state.viewerDoc,q=$('#viewerAiInput').value.trim();if(!d||!q)return;$('#viewerAiChat').insertAdjacentHTML('beforeend',`<div class="msg user">${escapeHtml(q)}</div>`);$('#viewerAiInput').value='';const cfg=loadApiConfig();if(!cfg.key){$('#viewerAiChat').insertAdjacentHTML('beforeend','<div class="msg bot">IA no configurada. Guardá tu API Key de Gemini una sola vez en Ajustes.</div>');return}const wantsWeb=/(actualiz|vigent|hoy|actualmente|reciente|últim|ultima|novedad|cambió|cambio|internet|fuera del documento|fuentes externas|fuera de este documento)/i.test(q);let webContext='';let webSources=[];if(wantsWeb&&navigator.onLine){const direct=await directWebSearch(q);webSources=direct;webContext=direct.length?`\n\nCONTEXTO WEB EXTERNO (no confundir con el documento):\n${direct.map(x=>`FUENTE: ${x.title}\nURL: ${x.url}\n${x.text}`).join('\n\n')}`:''}const prompt=`Sos el asistente documental de NEXUS-X. Respondé en español.\n\nREGLA PRINCIPAL: si la pregunta se refiere al contenido del documento, respondé primero y estrictamente con el documento. No inventes. Si el documento no contiene la respuesta, decilo.\n\nSi se incluyó CONTEXTO WEB EXTERNO, úsalo únicamente para comprobar actualidad o ampliar la pregunta cuando corresponda. Separá explícitamente: “Según el documento” y “Comprobación en Internet”. No presentes una fuente web como si estuviera en el documento.\n\n${documentContext(d)}${webContext}\n\nPREGUNTA: ${q}`;try{let requestInput=prompt;if(d.type==='PDF'&&d.blob){const b64=await blobToBase64(d.blob);requestInput=[{type:'document',data:b64,mime_type:'application/pdf'},{type:'text',text:prompt}]};const data=await geminiRequest(requestInput,{web:false});let ans=extractGeminiText(data)||'Sin respuesta';if(wantsWeb){ans+=webSources.length?'\n\nComprobación web realizada con fuentes externas.':'\n\nNo fue posible realizar una comprobación web; la respuesta se basa únicamente en el documento.'}$('#viewerAiChat').insertAdjacentHTML('beforeend',`<div class="msg bot">${escapeHtml(ans)}</div>`);if(webSources.length)$('#viewerAiChat').insertAdjacentHTML('beforeend',`<div class="footer-note">Fuentes web consultadas: ${webSources.slice(0,5).map(x=>x.url?`<a href="${escapeHtml(x.url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(x.title)}</a>`:escapeHtml(x.title)).join(' · ')}</div>`)}catch(e){$('#viewerAiChat').insertAdjacentHTML('beforeend',`<div class="msg bot">No se pudo consultar Gemini: ${escapeHtml(e.message)}. El documento sigue disponible para lectura local.</div>`)}$('#viewerAiChat').scrollTop=$('#viewerAiChat').scrollHeight}

async function aiQuery(){
 const q=$('#aiInput').value.trim();if(!q)return;$('#chat').insertAdjacentHTML('beforeend',`<div class="msg user">${escapeHtml(q)}</div>`);$('#aiInput').value='';
 const cfg=loadApiConfig();if(!cfg.key){$('#chat').insertAdjacentHTML('beforeend','<div class="msg bot">IA no configurada. Pegá tu API Key de Gemini una sola vez en Ajustes.</div>');return}
 const hits=searchLocal(state.lastQuery||q).slice(0,8),docHits=documentSearch(state.lastQuery||q).slice(0,10);
 const context=[...hits.map(x=>`ENTIDAD | ${x.r.id} | ${x.r.name} | ${x.r.formula} | ${x.r.location}`),...docHits.map(x=>`DOCUMENTO | ${x.d.name} | fragmento ${x.index+1} | ${x.chunk.slice(0,1200)}`)].join('\n');
 try{const data=await geminiRequest(`Sos NEXUS-X. Respondé en español. Separá evidencia local de inferencia y contexto web. No inventes datos.\n\nCONTEXTO LOCAL:\n${context||'Sin coincidencias locales.'}\n\nCONSULTA:\n${q}`,{web:false});const ans=extractGeminiText(data)||'Sin respuesta';$('#chat').insertAdjacentHTML('beforeend',`<div class="msg bot">${escapeHtml(ans)}</div>`)}catch(e){$('#chat').insertAdjacentHTML('beforeend',`<div class="msg bot">No se pudo consultar la IA: ${escapeHtml(e.message)}.</div>`)}$('#chat').scrollTop=$('#chat').scrollHeight;
}
function exportCsv(){const headers=['ID_NEXUS_X','Nº_Original','Sustancia_Mezcla_Material','Formula','Estado_Fisico','Presentacion','Envase_Original','Fecha_Envasado_Vencimiento','Ubicacion_Armario','Observaciones'];const map=r=>[r.id,r.originalNumber,r.name,r.formula,r.physicalState,r.presentation,r.originalPackage,r.expiry,r.location,r.notes];const csv=[headers,...state.inventory.map(map)].map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n');download('NEXUS-X-inventario.csv',new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));}
function exportReport(){const report={generatedAt:new Date().toISOString(),records:state.inventory.length,idsValid:state.inventory.every(x=>validId(x.id)),uniqueIds:new Set(state.inventory.map(x=>x.id)).size,locations:[...new Set(state.inventory.map(x=>x.location).filter(Boolean))],documents:state.docs};download('NEXUS-X-informe.json',new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));}
function download(name,blob){const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function renderReports(){const inv=state.inventory;$('#reportSummary').innerHTML=`<p><strong>${inv.length}</strong> registros</p><p><strong>${new Set(inv.map(x=>x.id)).size}</strong> IDs únicos</p><p><strong>${new Set(inv.map(x=>x.location).filter(Boolean)).size}</strong> ubicaciones</p><p><strong>${inv.filter(x=>x.formula).length}</strong> con fórmula</p>`;$('#integrityBox').textContent=JSON.stringify(runIntegrity(),null,2);}
function runIntegrity(){const ids=state.inventory.map(x=>x.id);return {ok:ids.length===111&&ids.every(validId)&&new Set(ids).size===ids.length,recordCount:ids.length,first:ids[0]||null,last:ids.at(-1)||null,uniqueIds:new Set(ids).size,duplicateIds:ids.filter((x,i)=>ids.indexOf(x)!==i),identityRule:'1 registro = 1 ID NEXUS-X'};}
function renderDiagnostics(){const cfg=loadApiConfig(),repo=activeRepo();const settings={provider:cfg.provider||'gemini',apiKey:cfg.key?'guardada localmente':'no configurada',web:state.web?'ON':'OFF',repo:`${repo.owner}/${repo.name}@${repo.branch||'main'}`,documents:state.docs.length};$('#settingsDiag').textContent=JSON.stringify({integrity:runIntegrity(),settings},null,2)}
function toggleFavorite(id){if(state.favorites.has(id))state.favorites.delete(id);else state.favorites.add(id);localStorage.setItem('nexus_x_favorites_v1',JSON.stringify([...state.favorites]));saveActivity(`${state.favorites.has(id)?'Favorito agregado':'Favorito quitado'}: ${id}`);renderInventory();}
function saveQueryHistory(q){if(!q)return;const key='nexus_x_queries_v1';let arr=[];try{arr=JSON.parse(localStorage.getItem(key)||'[]')}catch{};arr=[q,...arr.filter(x=>x!==q)].slice(0,8);localStorage.setItem(key,JSON.stringify(arr));renderQueryHistory();}
function renderQueryHistory(){const el=$('#researchHistory');if(!el)return;let arr=[];try{arr=JSON.parse(localStorage.getItem('nexus_x_queries_v1')||'[]')}catch{};el.innerHTML=arr.length?'<div class="footer-note">Consultas recientes</div><div class="toolbar">'+arr.map(q=>`<button class="btn" data-history="${escapeHtml(q)}">${escapeHtml(q)}</button>`).join('')+'</div>':'';$$('[data-history]').forEach(b=>b.onclick=()=>{$('#researchInput').value=b.dataset.history;runResearch()});}
function updateNetworkStatus(){const el=$('#networkStatus');if(!el)return;el.classList.toggle('offline',!navigator.onLine);el.innerHTML=`<span class="status-dot"></span>${navigator.onLine?'Local · online':'Modo local · offline'}`;}
function openCommandPalette(){const items=[['⌕','Buscar en inventario','Ir a Inventario y enfocar búsqueda','inventory'],['⚗','Investigar','Abrir Investigación','research'],['⌗','Escanear QR','Abrir Escáner QR','qr'],['▤','Documentos','Abrir Documentos','documents'],['⌁','Informe','Abrir Informes','reports'],['⚙','Ajustes','Abrir Ajustes','settings']];$('#commandList').innerHTML=items.map(x=>`<button class="command-item" data-command="${x[3]}"><span><strong>${x[0]} ${x[1]}</strong><br><span class="muted">${x[2]}</span></span><span class="kbd">Enter</span></button>`).join('');$$('[data-command]').forEach(b=>b.onclick=()=>{setView(b.dataset.command);$('#commandModal').classList.remove('open');if(b.dataset.command==='inventory')setTimeout(()=>$('#inventorySearch').focus(),50)});$('#commandModal').classList.add('open');}
function renderAll(){renderDashboard();renderActivity();renderInventory();renderDiagnostics();}
async function syncRepository(){
 const status=$('#repoStatus');status.textContent='Descubriendo archivos…';state.docSyncing=true;renderDocuments();
 const repo=activeRepo();
 try{
  const apiBase=`https://api.github.com/repos/${encodeURIComponent(repo.owner)}/${encodeURIComponent(repo.name)}`;
  const treeRes=await fetchTimeout(`${apiBase}/git/trees/${encodeURIComponent(repo.branch||'main')}?recursive=1`,{headers:{Accept:'application/vnd.github+json'}},12000);
  if(!treeRes.ok)throw new Error(`GitHub HTTP ${treeRes.status}`);
  const tree=await treeRes.json();
  const files=(tree.tree||[]).filter(x=>x.type==='blob');
  const supported=files.filter(x=>/\.(pdf|docx|xlsx|xls|csv|txt|md)$/i.test(x.path));
  status.textContent=`${supported.length} documentos · indexando…`;
  let ok=0; let failed=[];
  for(const f of supported){
   if(Number(f.size||0)>DOC_MAX_BYTES){console.warn('Documento omitido por tamaño',f.path);failed.push({path:f.path,error:'Supera el límite local de 6 MB'});continue}
   try{
    const url=`https://raw.githubusercontent.com/${encodeURIComponent(repo.owner)}/${encodeURIComponent(repo.name)}/${encodeURIComponent(repo.branch||'main')}/${f.path.split('/').map(encodeURIComponent).join('/')}`;
    const res=await fetchTimeout(url,{cache:'no-store'},15000);if(!res.ok)throw new Error(`HTTP ${res.status}`);const blob=await res.blob();let text='',type=docType(f.path);
    if(type==='DOCX'){const parsed=await JSZipReady(blob);text=parsed.text}
    else if(type==='PDF'){await loadScript('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js','pdfjsLib');if(window.pdfjsLib?.GlobalWorkerOptions)window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const pdf=await pdfjsLib.getDocument({data:await blob.arrayBuffer()}).promise;const pages=[];for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n),content=await page.getTextContent();pages.push(`PÁGINA ${n}\n`+content.items.map(x=>x.str||'').join(' '))}text=pages.join('\n\n')}
    else if(type==='XLSX'||type==='XLS'){await loadScript('https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js','XLSX');const wb=XLSX.read(await blob.arrayBuffer(),{type:'array',cellDates:true,raw:false,defval:''});text=wb.SheetNames.map(name=>`HOJA: ${name}\n`+XLSX.utils.sheet_to_csv(wb.Sheets[name])).join('\n\n')}
    else text=await blob.text();
    await indexDocument({name:f.path.split('/').pop(),path:f.path,type,size:f.size,text,source:`GitHub · ${repo.owner}/${repo.name}`,url,blob,mime:blob.type});ok++;
   }catch(e){console.warn('Documento GitHub',f.path,e);failed.push({path:f.path,error:e.message||String(e)})}
  }
  state.docSyncing=false;renderDocuments();status.textContent=`OK · ${ok}/${supported.length} documentos indexados`;saveActivity(`Repositorio indexado: ${ok}/${supported.length} documentos`);renderDashboard();if(failed.length){toast(`${failed.length} documento(s) no pudieron indexarse. Revisá el diagnóstico documental.`);$('#documentList')?.insertAdjacentHTML('afterbegin',`<div class="notice warn"><strong>Documentos con problemas:</strong><br>${failed.map(x=>escapeHtml(x.path)+' — '+escapeHtml(x.error)).join('<br>')}</div>`)}
 }catch(e){state.docSyncing=false;console.warn(e);status.textContent='No disponible';renderDocuments();toast(`No se pudo sincronizar ${repo.owner}/${repo.name}: ${e.message}`)}
}
async function JSZipReady(blob){await loadScript('https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js','JSZip');const zip=await JSZip.loadAsync(await blob.arrayBuffer());const xml=await zip.file('word/document.xml').async('text');const doc=new DOMParser().parseFromString(xml,'application/xml');const text=[...doc.getElementsByTagName('w:p')].map(p=>[...p.getElementsByTagName('w:t')].map(t=>t.textContent||'').join('').trim()).filter(Boolean).join('\n');return {text}}
const CAL_KEY='nexus_x_calendar_v1';let calCursor=new Date();
function calendarEvents(){try{return JSON.parse(localStorage.getItem(CAL_KEY)||'[]')}catch{return[]}}
function saveCalendarEvents(events){localStorage.setItem(CAL_KEY,JSON.stringify(events))}
function pad2(n){return String(n).padStart(2,'0')}
function isoDate(d){return `${d.getFullYear()}-${pad2(d.getMonth()+1)}-${pad2(d.getDate())}`}
function renderCalendar(){const y=calCursor.getFullYear(),m=calCursor.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),start=(first.getDay()+6)%7;const events=calendarEvents();$('#calTitle').textContent=new Intl.DateTimeFormat('es-AR',{month:'long',year:'numeric'}).format(first).replace(/^./,c=>c.toUpperCase());const heads=['L','M','M','J','V','S','D'];let html=heads.map(x=>`<div class="dow">${x}</div>`).join('');for(let i=0;i<start;i++)html+='<div class="day muted-day"></div>';for(let d=1;d<=last.getDate();d++){const date=new Date(y,m,d),key=isoDate(date),dayEvents=events.filter(e=>e.date===key);html+=`<button type="button" class="day ${key===isoDate(new Date())?'today ':''}${dayEvents.length?'has-event':''}" data-cal-date="${key}"><span class="num">${d}</span>${dayEvents.slice(0,2).map(e=>`<span class="dot">• ${escapeHtml(e.text)}</span>`).join('')}</button>`}const total=Math.ceil((start+last.getDate())/7)*7;for(let i=start+last.getDate();i<total;i++)html+='<div class="day muted-day"></div>';$('#calGrid').innerHTML=html;$$('[data-cal-date]').forEach(b=>b.onclick=()=>{$('#calDate').value=b.dataset.calDate;$('#calEvent').focus();});const grouped=events.filter(e=>e.date>=isoDate(new Date(y,m,1))&&e.date<=isoDate(last)).sort((a,b)=>a.date.localeCompare(b.date));$('#calEvents').innerHTML=grouped.length?grouped.map((e,i)=>`<div class="calendar-event"><span><strong>${escapeHtml(e.date)}</strong> · ${escapeHtml(e.text)}</span><button class="btn danger" data-cal-delete="${i}">Eliminar</button></div>`).join(''):'Sin eventos para este mes.';$$('[data-cal-delete]').forEach((b)=>b.onclick=()=>{const target=grouped[Number(b.dataset.calDelete)];saveCalendarEvents(events.filter(e=>!(e.date===target.date&&e.text===target.text)));renderCalendar()})}
function openCalendar(){calCursor=new Date();$('#calDate').value=isoDate(calCursor);$('#calEvent').value='';$('#calendarModal').classList.add('open');renderCalendar()}
function addCalendarEvent(){const date=$('#calDate').value,text=$('#calEvent').value.trim();if(!date||!text){toast('Indicá fecha y evento.');return}const events=calendarEvents();events.push({date,text});events.sort((a,b)=>a.date.localeCompare(b.date));saveCalendarEvents(events);$('#calEvent').value='';renderCalendar();saveActivity(`Evento agregado: ${text}`);toast('Evento agregado al calendario.')}

function bind(){
 updateNetworkStatus();window.addEventListener('online',updateNetworkStatus);window.addEventListener('offline',updateNetworkStatus);$('#commandBtn').onclick=openCommandPalette;window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommandPalette()}if(e.key==='Escape')$$('.modal-backdrop.open').forEach(m=>m.classList.remove('open'))});renderQueryHistory();
 $$('.nav-btn').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$$('.research-tab').forEach(b=>b.addEventListener('click',()=>setResearchTab(b.dataset.tab)));$('#syncRepoBtn').onclick=syncRepository;$('#syncRepoSettingsBtn').onclick=syncRepository;
 $('#globalSearchBtn').onclick=()=>{const q=$('#globalSearch').value.trim();if(q){setView('research');$('#researchInput').value=q;runResearch()}};$('#globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter')$('#globalSearchBtn').click()});
 $('#webToggle').onclick=()=>{state.web=!state.web;$('#webToggle').textContent=`🌐 Internet: ${state.web?'ON':'OFF'}`;toast(state.web?'Búsqueda web activada.':'Búsqueda web desactivada.');if(state.web&&state.lastQuery)runWeb(state.lastQuery)};
 $('#inventorySearch').oninput=renderInventory;$('#locationFilter').onchange=renderInventory;$('#statusFilter').onchange=renderInventory;$('#newItemBtn').onclick=newItem;$('#saveItemBtn').onclick=saveItem;$('#deleteItemBtn').onclick=deleteItem;$('#exportExcelBtn').onclick=exportCsv;$('#importExcelBtn').onclick=()=>$('#excelInput').click();$('#excelInput').onchange=e=>{const f=e.target.files[0];if(f)importExcel(f);e.target.value=''};
 $('#researchBtn').onclick=runResearch;$('#researchInput').addEventListener('keydown',e=>{if(e.key==='Enter')runResearch()});$('#aiBtn').onclick=aiQuery;$('#aiInput').addEventListener('keydown',e=>{if(e.key==='Enter')aiQuery()});
 $('#startQrBtn').onclick=startQr;$('#stopQrBtn').onclick=stopQr;$('#qrImage').onchange=e=>{const f=e.target.files[0];if(f)decodeQrImage(f);e.target.value=''};$('#manualQrBtn').onclick=()=>{if($('#manualQr').value.trim())processQr($('#manualQr').value)};
 $('#loadWordBtn').onclick=()=>$('#wordInput').click();$('#wordInput').onchange=e=>{const f=e.target.files[0];if(f)importWord(f);e.target.value=''};$('#loadPdfBtn').onclick=()=>$('#pdfInput').click();$('#pdfInput').onchange=e=>{const f=e.target.files[0];if(f)importPdf(f);e.target.value=''};$('#loadDocumentBtn').onclick=()=>$('#documentInput').click();$('#documentInput').onchange=e=>{const f=e.target.files[0];if(f)importDocumentFile(f);e.target.value=''};$('#resetMasterBtn').onclick=loadMaster;
 $('#exportReportBtn').onclick=exportReport;$('#viewerCloseBtn').onclick=closeDocumentViewer;$('#viewerAiBtn').onclick=openDocumentAI;$('#viewerDocumentBtn').onclick=()=>{if(state.viewerDoc){$('[data-viewer-tab="ai"]').classList.remove('active');$('[data-viewer-tab="document"]').classList.add('active');$('#viewerAiPane').style.display='none';$('#viewerDocumentPane').style.display='block'}};$('#viewerAskBtn').onclick=viewerAiAsk;$('#viewerAiInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();viewerAiAsk()}});$('#settingsBtn').onclick=()=>setView('settings');$('#saveApiBtn').onclick=saveApiSettings;$('#clearApiBtn').onclick=clearApiSettings;$('#saveRepoSettingsBtn').onclick=saveRepoSettings;$('#clearLocalBtn').onclick=()=>{if(confirm('¿Borrar cambios locales modificables? Se conservará la configuración de API y repositorio.')){localStorage.removeItem(DB_KEY);loadMaster()}};updateApiUi();
 $$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.remove('open'));$('#calendarBtn').onclick=openCalendar;$('#calPrev').onclick=()=>{calCursor.setMonth(calCursor.getMonth()-1);renderCalendar()};$('#calNext').onclick=()=>{calCursor.setMonth(calCursor.getMonth()+1);renderCalendar()};$('#calToday').onclick=()=>{calCursor=new Date();renderCalendar()};$('#calAdd').onclick=addCalendarEvent;$('#calEvent').addEventListener('keydown',e=>{if(e.key==='Enter')addCalendarEvent()});window.addEventListener('beforeunload',stopQr);
}
async function boot(){bind();state.repo=detectGitHubRepo();state.web=!!loadApiConfig().key;$('#webToggle').textContent=`🌐 Internet: ${state.web?'ON':'OFF'}`;updateApiUi();renderActivity();await loadCachedDocumentIndex();await loadMaster();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(console.warn);syncRepository();}
boot();
})();
